### ISSUE TITLE
src/database/sqlite3.c needs 800Mb to compile

### ISSUE THREAD

**Issue by L0ric0** [pi-hole/FTL#1121] opened 2021-04-22 15:30 UTC
### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  FTL-5.8.1

### Platform

- OS and version:  Archlinux 

- Platform:  Raspberry Pi 3B

### Expected behavior

pihole-FTL builds while keeping a sane memory consumption

### Actual behavior / bug

While building pihole-FTL the building of `src/database/sqlite3.c` consumes memory in the excess of 800MB´. this is enough to invoke the os oom handler and kills the compilation.

### Steps to reproduce

1. use a Respberry Pi with 900Mb main memory and an idle memory consumption of around 150MB
2. modify the `build.sh` to only use one core
3. run the build an watch it crash on building `src/database/sqlite3.c`

### Additional context

for an aplication targetet at respberry pis it should be possible to build it on sayed unit as nobody can be expected to have an arm pc at home with enough memory and the same architecture. therefor it would be nice to add an option to the buildprocess to use the systeminstallation of sqlite3 or split the `sqlite3.c` file in multiple translation units and enable linktime optimization.

**Comment by DL6ER** [comment] 2021-04-27 09:22
> for an aplication targetet at respberry pis it should be possible to build it on sayed unit 

I did that frequently before switching to cross-compiling on an x86 machine due to the massive speed difference and because FTL needs to be frequently recompiled during its development. I cannot reproduce your observation on a Raspberry Pi 1B+ running Raspbian. So this **may be an issue related to** you using **Archlinux** even when I cannot explain why this is the case.

> it would be nice to add an option to the buildprocess to use the systeminstallation of sqlite3

We are not talking about the `sqlite3` program here that is used but we're talking about a module that is really embedded into FTL. Using an already available `sqlite3` application on the system would have *many* drawbacks ranging from slowness (due to an interface) to issues with escaping (as we cannot natively bind variables).

> or split the `sqlite3.c` file in multiple translation units and enable linktime optimization

Would linktime optimization manage to complete? Would it really use less memory here? The SQLite3 source amalgamation is the recommended way to include SQLite3 in any other project and the way successfully employed by us and many other popular projects for quite a long time.

Hence, I will mark this as `Wontfix` and close this issue ticket. This because of the mentioned points above not because I don't want to help you. Mind that SQLite3 is an open-source third-party software using on billions of devices worldwide. We do not modify a single bit of it so this is really an issue that would need to be addressed upstream to its maintainers at https://www.sqlite.org

**Closed by DL6ER** 2021-04-27 09:22 UTC
