### ISSUE TITLE
Black list no longer working?

### ISSUE THREAD

**Issue by Khengsoon** [pi-hole/FTL#1085] opened 2021-03-20 07:25 UTC
Dear all, I'm running pihole v5.2.4 on raspberry pi. I'm testing the blacklist feature, the domain reg I added is (\.|^)youtube\.com$ how every I still able to go youtube.com. I make sure my DNS is set to my pihole, may I know what I missed out?

**Comment by yubiuser** [comment] 2021-03-20 07:47
You missed the debug token.

**Comment by yubiuser** [comment] 2021-03-20 07:48
Duplicate of https://github.com/pi-hole/pi-hole/issues/4087

**Comment by Khengsoon** [comment] 2021-03-20 07:54
Sorry for that my debug token is https://tricorder.pi-hole.net/wrs0nkkcxy

**Closed** 2021-03-21 04:16 UTC
