### ISSUE TITLE
Pihole-FTL: Received signal: Segmentation fault with code: SEGV_MAPERR 

### ISSUE THREAD

**Issue by waz452** [pi-hole/FTL#257] opened 2018-04-20 08:09 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:** 0
**[BUG | ISSUE] Expected Behaviour:**   
**[BUG | ISSUE] Actual Behaviour:**  
**[BUG | ISSUE] Steps to reproduce:**

-
-
**Log file output [if available]**

[2018-04-20 17:47:52.642] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2018-04-20 17:47:52.642] ---------------------------->  FTL crashed!  <----------------------------
[2018-04-20 17:47:52.642] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2018-04-20 17:47:52.642] Please report a bug at https://github.com/pi-hole/FTL/issues
[2018-04-20 17:47:52.642] and include in your report already the following details:

[2018-04-20 17:47:52.642] FTL has been running for -32218 seconds
[2018-04-20 17:47:52.642] FTL branch: FTLDNS
[2018-04-20 17:47:52.642] FTL version:
[2018-04-20 17:47:52.642] FTL commit: 3656ba2
[2018-04-20 17:47:52.642] FTL date: 2018-04-17 17:01:08 +0200
[2018-04-20 17:47:52.642] FTL user: pihole
[2018-04-20 17:47:52.642]
Received signal: Segmentation fault
[2018-04-20 17:47:52.642]      at address: 0
[2018-04-20 17:47:52.642]       with code: SEGV_MAPERR (Address not mapped to object)
[2018-04-20 17:47:52.642] Memory usage (structs): 680624
[2018-04-20 17:47:52.642] Memory usage (dynamic): 6663

[2018-04-20 17:47:52.642] Thank you for helping us to improve our FTL engine!
[2018-04-20 17:47:52.642] FTL terminated!

---

root@dnscore /etc/.pihole# service pihole-FTL status
* pihole-FTL.service - LSB: pihole-FTL daemon
   Loaded: loaded (/etc/init.d/pihole-FTL; generated; vendor preset: enabled)
   Active: active (running) since Fri 2018-04-20 18:06:38 AEST; 12s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2623 ExecStop=/etc/init.d/pihole-FTL stop (code=exited, status=0/SUCCESS)
  Process: 2627 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)
    Tasks: 6 (limit: 4915)
   CGroup: /system.slice/pihole-FTL.service
           `-2657 /usr/bin/pihole-FTL

Apr 20 18:06:38 dnscore systemd[1]: Starting LSB: pihole-FTL daemon...
Apr 20 18:06:38 dnscore pihole-FTL[2627]: Not running
Apr 20 18:06:38 dnscore pihole-FTL[2627]: chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
Apr 20 18:06:38 dnscore su[2653]: Successful su for pihole by root
Apr 20 18:06:38 dnscore su[2653]: + ??? root:pihole
Apr 20 18:06:38 dnscore su[2653]: pam_unix(su:session): session opened for user pihole by (uid=0)
Apr 20 18:06:38 dnscore pihole-FTL[2627]: FTL started!
Apr 20 18:06:38 dnscore su[2653]: pam_unix(su:session): session closed for user pihole
Apr 20 18:06:38 dnscore systemd[1]: Started LSB: pihole-FTL daemon.

----

**Device specifics**

Hardware Type: rPi, VPS, etc   VirtualBox running Turkey Linux upgraded to Stretch
OS:  Linux dnscore 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

so i dunno what i've done to get it working again .... but just thought i'd log this anyways in case it helps find a possible issue ..

**Comment by jheiselman** [comment] 2018-05-10 22:27
https://gist.github.com/jheiselman/748e7ba0abadc25db89ec91afe8aae5d

Got the same SEGFAULT. Link is to full log.

**Comment by DL6ER** [comment] 2018-05-11 05:52
@jheiselman can you reproduce the crash? If, please run FTL in the debugger. Instructions can be found here: https://docs.pi-hole.net/ftldns/debugging/

**Comment by DL6ER** [comment] 2018-05-11 05:53
@jheiselman can you reproduce the crash? If, please run FTL in the debugger. Instructions can be found here: https://docs.pi-hole.net/ftldns/debugging/

**Comment by jheiselman** [comment] 2018-05-11 14:00
@DL6ER I'll give it a try later today. I had to switch to a different DNS server since I needed the stability at the time.

**Comment by Mcat12** [comment] 2018-05-28 21:31
@jheiselman were you able to reproduce this?

**Comment by Watanuki-kun** [comment] 2018-05-28 23:06
I also got the same SEGFAULT today. Debug Token rh0qda4pxz

**Comment by DL6ER** [comment] 2018-05-29 07:46
@Watanuki-kun Thanks for your report. Can you please run the [debugging instructions](https://docs.pi-hole.net/ftldns/debugging/)?

**Comment by Watanuki-kun** [comment] 2018-05-29 22:45
@DL6ER Will do.

**Comment by Mcat12** [comment] 2018-07-27 02:58
Any update on this? Try with the latest dev or FTLDNS build. It might be similar to the above referenced issue.

**Comment by jheiselman** [comment] 2018-08-02 13:14
I updated to the latest version and the system seems stable. It should probably be noted that the system was not under load during my test as I moved the responsibility for DNS-based adblocking from my raspberry pi to my router, so the testing may not be exposing the problem that was present before.

**Comment by Watanuki-kun** [comment] 2018-08-05 02:46
@Mcat12 I haven't experienced the issue since that day strangely. But like jheiselman, I updated to the latest build and will report back if I experience the issue again.

**Comment by Mcat12** [comment] 2018-08-05 03:51
Thanks for the responses. I will close the issue, but if it happens again it can be reopened.

**Closed by Mcat12** 2018-08-05 03:51 UTC
Labels: Potential bug
