### ISSUE TITLE
FTL 5.3.4 keeps updating to same version

### ISSUE THREAD

**Issue by boguscoder** [pi-hole/FTL#1019] opened 2021-01-14 08:13 UTC
### Versions
  Pi-hole version is v5.2.2 (Latest: v5.2.2)
  AdminLTE version is v5.2.2 (Latest: v5.2.2)
  FTL version is v5.3.4 (Latest: v5.3.4)

### Platform
- OS and version:  
- DietPi v6.34.3
- Platform:  
- RPi Zero W

### Expected behavior

`pihole -up` should not update FTL when on v 5.3.4

### Actual behavior / bug

`pihole -up` keeps updating FTL to 5.3.4 even after successful update to the same version, it goes through full update process with every attempt

### Steps to reproduce

`pihole -up` few times in a row when being on FTL 5.3.4

**Comment by yubiuser** [comment] 2021-01-14 08:56
Thanks for the report.
It's a duplicate of 
https://github.com/pi-hole/pi-hole/issues/3986

**Closed** 2021-01-14 18:06 UTC
