### ISSUE TITLE
FTL crashed with SQL 21 error, previously worked fine

### ISSUE THREAD

**Issue by zoltanhans** [pi-hole/FTL#114] opened 2017-07-16 06:53 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

7
---

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**Log file output [if available]**

`output`

Finished initial log file parsing
[2017-07-16 08:47:23.472]  -> Total DNS queries: 9090
[2017-07-16 08:47:23.472]  -> Cached DNS queries: 2380
[2017-07-16 08:47:23.472]  -> Blocked DNS queries: 388
[2017-07-16 08:47:23.472]  -> Unknown DNS queries: 0
[2017-07-16 08:47:23.472]  -> Unique domains: 999
[2017-07-16 08:47:23.472]  -> Unique clients: 13
[2017-07-16 08:47:23.472] Successfully accessed setupVars.conf
[2017-07-16 08:47:23.473] Listening on port 4711 for incoming connections
[2017-07-16 08:48:00.023] SQL error (21): (null)
[2017-07-16 08:48:00.024] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2017-07-16 08:48:00.024] ---------------------------->  FTL crashed!  <----------------------------
[2017-07-16 08:48:00.024] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2017-07-16 08:48:00.024] > Please report a bug at https://github.com/pi-hole/FTL/issues
[2017-07-16 08:48:00.024] > and include in your report already the following details:
[2017-07-16 08:48:00.025] >
[2017-07-16 08:48:00.025] > Received signal: Segmentation fault
[2017-07-16 08:48:00.025]        at address: 0
[2017-07-16 08:48:00.025]         with code: SEGV_MAPERR (Address not mapped to object)
[2017-07-16 08:48:00.025] > Memory usage (structs): 346944
[2017-07-16 08:48:00.025] > Memory usage (dynamic): 23455
[2017-07-16 08:48:00.026] >
[2017-07-16 08:48:00.026] > Thank you for helping us to improve our FTL engine!
[2017-07-16 08:48:00.026] FTL terminated!

**Device specifics**

Hardware Type: rPi, VPS, etc: banana pi R1
OS: 3.4.113-bananian

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment] 2017-07-16 18:35
Duplicate of #112, will be fixed by #113.

**Comment by DL6ER** [comment] 2017-09-03 11:32
Fix (#113) has been released almost one month ago.

Feel free to either re-open this issue or open a new one with new information if you are still affected by this bug.

**Closed by DL6ER** 2017-09-03 11:32 UTC
Labels: Bug, Duplicate
