### ISSUE TITLE
FTL Crashes randomly

### ISSUE THREAD

**Issue by shohart** [pi-hole/FTL#706] opened 2020-03-04 08:34 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [*] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [*] The issue I am reporting can be *replicated*
- [*] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

5 {replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---

**[BUG | ISSUE] Expected Behaviour:**

normal operation

**[BUG | ISSUE] Actual Behaviour:**

random crashes

**[BUG | ISSUE] Steps to reproduce:**
-
-
-
-

**Log file output [if available]**

[2020-03-04 00:53:07.399 14524] Using log file /var/log/pihole-FTL.log
[2020-03-04 00:53:07.399 14524] ########## FTL started! ##########
[2020-03-04 00:53:07.399 14524] FTL branch: master
[2020-03-04 00:53:07.399 14524] FTL version: v4.3.1
[2020-03-04 00:53:07.399 14524] FTL commit: b60d63f
[2020-03-04 00:53:07.399 14524] FTL date: 2019-05-25 21:37:26 +0200
[2020-03-04 00:53:07.399 14524] FTL user: root
[2020-03-04 00:53:07.400 14524] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
[2020-03-04 00:53:07.400 14524]    SOCKET_LISTENING: only local
[2020-03-04 00:53:07.400 14524]    AAAA_QUERY_ANALYSIS: Show AAAA queries
[2020-03-04 00:53:07.400 14524]    MAXDBDAYS: max age for stored queries is 365 days
[2020-03-04 00:53:07.400 14524]    RESOLVE_IPV6: Resolve IPv6 addresses
[2020-03-04 00:53:07.400 14524]    RESOLVE_IPV4: Resolve IPv4 addresses
[2020-03-04 00:53:07.400 14524]    DBINTERVAL: saving to DB file every minute
[2020-03-04 00:53:07.400 14524]    DBFILE: Using /etc/pihole/pihole-FTL.db
[2020-03-04 00:53:07.400 14524]    MAXLOGAGE: Importing up to 24.0 hours of log data
[2020-03-04 00:53:07.400 14524]    PRIVACYLEVEL: Set to 0
[2020-03-04 00:53:07.400 14524]    IGNORE_LOCALHOST: Show queries from localhost
[2020-03-04 00:53:07.400 14524]    BLOCKINGMODE: Null IPs for blocked domains
[2020-03-04 00:53:07.400 14524]    ANALYZE_ONLY_A_AND_AAAA: Enabled. Analyzing only A and AAAA queries
[2020-03-04 00:53:07.400 14524]    DBIMPORT: Importing history from database
[2020-03-04 00:53:07.400 14524]    PIDFILE: Using /var/run/pihole-FTL.pid
[2020-03-04 00:53:07.400 14524]    PORTFILE: Using /var/run/pihole-FTL.port
[2020-03-04 00:53:07.400 14524]    SOCKETFILE: Using /var/run/pihole/FTL.sock
[2020-03-04 00:53:07.400 14524]    WHITELISTFILE: Using /etc/pihole/whitelist.txt
[2020-03-04 00:53:07.400 14524]    BLACKLISTFILE: Using /etc/pihole/black.list
[2020-03-04 00:53:07.400 14524]    GRAVITYFILE: Using /etc/pihole/gravity.list
[2020-03-04 00:53:07.400 14524]    REGEXLISTFILE: Using /etc/pihole/regex.list
[2020-03-04 00:53:07.400 14524]    SETUPVARSFILE: Using /etc/pihole/setupVars.conf
[2020-03-04 00:53:07.400 14524]    AUDITLISTFILE: Using /etc/pihole/auditlog.list
[2020-03-04 00:53:07.400 14524]    MACVENDORDB: Using /etc/pihole/macvendor.db
[2020-03-04 00:53:07.400 14524]    PARSE_ARP_CACHE: Active
[2020-03-04 00:53:07.400 14524] Finished config file parsing
[2020-03-04 00:53:07.401 14524] WARNING: Starting pihole-FTL as user root is not recommended
[2020-03-04 00:53:07.409 14524] Database version is 3
[2020-03-04 00:53:07.409 14524] Database successfully initialized
[2020-03-04 00:53:07.411 14524] New forward server: 1.0.0.1 (0/512)
[2020-03-04 00:53:07.412 14524] New forward server: 1.1.1.1 (1/512)
[2020-03-04 00:53:07.423 14524] Resizing "/FTL-queries" from 229376 to 458752
[2020-03-04 00:53:07.425 14524] New forward server: 127.0.0.1 (2/512)
[2020-03-04 00:53:07.430 14524] Resizing "/FTL-queries" from 458752 to 688128
[2020-03-04 00:53:07.430 14524] Resizing "/FTL-strings" from 4096 to 8192
[2020-03-04 00:53:07.439 14524] Resizing "/FTL-queries" from 688128 to 917504
[2020-03-04 00:53:07.448 14524] Resizing "/FTL-queries" from 917504 to 1146880
[2020-03-04 00:53:07.448 14524] Resizing "/FTL-strings" from 8192 to 12288
[2020-03-04 00:53:07.455 14524] Resizing "/FTL-strings" from 12288 to 16384
[2020-03-04 00:53:07.461 14524] Resizing "/FTL-strings" from 16384 to 20480
[2020-03-04 00:53:07.461 14524] Resizing "/FTL-queries" from 1146880 to 1376256
[2020-03-04 00:53:07.470 14524] Resizing "/FTL-queries" from 1376256 to 1605632
[2020-03-04 00:53:07.480 14524] Resizing "/FTL-strings" from 20480 to 24576
[2020-03-04 00:53:07.481 14524] Resizing "/FTL-queries" from 1605632 to 1835008
[2020-03-04 00:53:07.495 14524] Resizing "/FTL-queries" from 1835008 to 2064384
[2020-03-04 00:53:07.502 14524] Resizing "/FTL-queries" from 2064384 to 2293760
[2020-03-04 00:53:07.507 14524] Resizing "/FTL-strings" from 24576 to 28672
[2020-03-04 00:53:07.511 14524] Resizing "/FTL-queries" from 2293760 to 2523136
[2020-03-04 00:53:07.517 14524] Resizing "/FTL-strings" from 28672 to 32768
[2020-03-04 00:53:07.518 14524] Resizing "/FTL-queries" from 2523136 to 2752512
[2020-03-04 00:53:07.530 14524] Resizing "/FTL-queries" from 2752512 to 2981888
[2020-03-04 00:53:07.534 14524] Imported 50348 queries from the long-term database
[2020-03-04 00:53:07.535 14524]  -> Total DNS queries: 50348
[2020-03-04 00:53:07.535 14524]  -> Cached DNS queries: 26416
[2020-03-04 00:53:07.535 14524]  -> Forwarded DNS queries: 21099
[2020-03-04 00:53:07.535 14524]  -> Exactly blocked DNS queries: 2803
[2020-03-04 00:53:07.535 14524]  -> Unknown DNS queries: 30
[2020-03-04 00:53:07.535 14524]  -> Unique domains: 1524
[2020-03-04 00:53:07.535 14524]  -> Unique clients: 16
[2020-03-04 00:53:07.535 14524]  -> Known forward destinations: 3
[2020-03-04 00:53:07.535 14524] Successfully accessed setupVars.conf
[2020-03-04 00:53:07.540 14531] PID of FTL process: 14531
[2020-03-04 00:53:07.540 14531] Listening on port 4711 for incoming IPv4 telnet connections
[2020-03-04 00:53:07.541 14531] Error listening on IPv6 port 4711: Cannot assign requested address (99)
[2020-03-04 00:53:07.541 14531] Listening on Unix socket
[2020-03-04 00:53:07.542 14531] Received SIGHUP, reloading cache
[2020-03-04 00:53:07.542 14531] Blocking status is enabled
[2020-03-04 00:53:07.546 14531] Compiled 1 Regex filters and 38 whitelisted domains in 3.2 msec (0 errors)
[2020-03-04 00:53:07.546 14531] /etc/pihole/black.list: parsed 5 domains (took 0.0 ms)
[2020-03-04 00:53:07.970 14531] /etc/pihole/gravity.list: parsed 171641 domains (took 423.5 ms)
[2020-03-04 00:54:00.091 14531] Resizing "/FTL-strings" from 32768 to 36864
[2020-03-04 01:00:00.231 14531] Notice: Database size is 947.25 MB, deleted 590 rows
[2020-03-04 02:00:00.194 14531] Notice: Database size is 947.25 MB, deleted 459 rows
[2020-03-04 02:59:00.125 14531] Notice: Database size is 947.25 MB, deleted 351 rows
[2020-03-04 04:00:00.205 14531] Notice: Database size is 947.25 MB, deleted 1861 rows
[2020-03-04 04:59:00.185 14531] Notice: Database size is 947.25 MB, deleted 347 rows
[2020-03-04 05:59:00.159 14531] Notice: Database size is 947.25 MB, deleted 392 rows
[2020-03-04 06:00:06.829 14531] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-03-04 06:00:06.829 14531] ---------------------------->  FTL crashed!  <----------------------------
[2020-03-04 06:00:06.829 14531] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-03-04 06:00:06.829 14531] Please report a bug at https://github.com/pi-hole/FTL/issues
[2020-03-04 06:00:06.829 14531] and include in your report already the following details:
[2020-03-04 06:00:06.829 14531] FTL has been running for 18419 seconds
[2020-03-04 06:00:06.829 14531] FTL branch: master
[2020-03-04 06:00:06.829 14531] FTL version: v4.3.1
[2020-03-04 06:00:06.829 14531] FTL commit: b60d63f
[2020-03-04 06:00:06.829 14531] FTL date: 2019-05-25 21:37:26 +0200
[2020-03-04 06:00:06.829 14531] FTL user: started as root, ended as root
[2020-03-04 06:00:06.829 14531] Received signal: Segmentation fault
[2020-03-04 06:00:06.829 14531]      at address: 0
[2020-03-04 06:00:06.829 14531]      with code: SEGV_MAPERR (Address not mapped to object)
[2020-03-04 06:00:06.830 14531] Backtrace:
[2020-03-04 06:00:06.830 14531] B[0000]: /usr/bin/pihole-FTL(+0x255e5) [0x55f7c48265e5]
[2020-03-04 06:00:06.830 14531] B[0001]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0) [0x7f710946e0e0]
[2020-03-04 06:00:06.830 14531] B[0002]: /usr/bin/pihole-FTL(+0x47a9a) [0x55f7c4848a9a]
[2020-03-04 06:00:06.830 14531] B[0003]: /usr/bin/pihole-FTL(receive_query+0x905) [0x55f7c4849e05]
[2020-03-04 06:00:06.830 14531] B[0004]: /usr/bin/pihole-FTL(+0x5db5b) [0x55f7c485eb5b]
[2020-03-04 06:00:06.830 14531] B[0005]: /usr/bin/pihole-FTL(main_dnsmasq+0xfdc) [0x55f7c486067c]
[2020-03-04 06:00:06.830 14531] B[0006]: /usr/bin/pihole-FTL(main+0xbc) [0x55f7c4824acc]
[2020-03-04 06:00:06.830 14531] B[0007]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f71090de2e1]
[2020-03-04 06:00:06.830 14531] B[0008]: /usr/bin/pihole-FTL(_start+0x2a) [0x55f7c4824bfa]
[2020-03-04 06:00:06.830 14531] Thank you for helping us to improve our FTL engine!
[2020-03-04 06:00:06.830 14531] FTL terminated!
**Device specifics**

Hardware Type: rPi, VPS, etc
OS: Debian 9

**Comment by PromoFaux** [comment] 2020-03-04 08:37
Looks to be a duplicate of #704

**Comment by PromoFaux** [comment] 2020-03-04 09:40
Closing out in favour of https://github.com/pi-hole/FTL/issues/705, as most of the discussion is happening there.

It appears to be dnssec related, and workaround for now is to disable that until cloudflare have resolved their upstream issue.

Another alternative is to be your own recursive DNS server:

https://docs.pi-hole.net/guides/unbound/

**Closed by PromoFaux** 2020-03-04 09:40 UTC
