### ISSUE TITLE
FTL crashed 

### ISSUE THREAD

**Issue by actng** [pi-hole/FTL#801] opened 2020-05-31 20:12 UTC
[2020-05-31 06:11:26.724 882] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-05-31 06:11:26.724 882] ---------------------------->  FTL crashed!  <----------------------------
[2020-05-31 06:11:26.724 882] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-05-31 06:11:26.724 882] Please report a bug at https://github.com/pi-hole/FTL/issues
[2020-05-31 06:11:26.724 882] and include in your report already the following details:
[2020-05-31 06:11:26.724 882] FTL has been running for 64132 seconds
[2020-05-31 06:11:26.724 882] FTL branch: master
[2020-05-31 06:11:26.724 882] FTL version: v5.0
[2020-05-31 06:11:26.724 882] FTL commit: 3d7c095
[2020-05-31 06:11:26.724 882] FTL date: 2020-05-10 18:58:38 +0100
[2020-05-31 06:11:26.724 882] FTL user: started as pihole, ended as pihole
[2020-05-31 06:11:26.724 882] Compiled for x86_64 (compiled on CI) using gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
[2020-05-31 06:11:26.724 882] Received signal: Segmentation fault
[2020-05-31 06:11:26.724 882]      at address: (nil)
[2020-05-31 06:11:26.724 882]      with code: Unknown (128)
[2020-05-31 06:11:26.725 882] Backtrace:
[2020-05-31 06:11:26.725 882] B[0000]: 0x561d0bf366f9, /usr/bin/pihole-FTL(+0x316f9) [0x561d0bf366f9]
[2020-05-31 06:11:26.725 882] B[0001]: 0x7fde6c8093c0, /lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0) [0x7fde6c8093c0]
[2020-05-31 06:11:26.725 882] B[0002]: 0x561d0bf6b6e0, /usr/bin/pihole-FTL(+0x666e0) [0x561d0bf6b6e0]
[2020-05-31 06:11:26.725 882] B[0003]: 0x561d0bf6d7bc, /usr/bin/pihole-FTL(main_dnsmasq+0x129c) [0x561d0bf6d7bc]
[2020-05-31 06:11:26.725 882] B[0004]: 0x561d0bf298ac, /usr/bin/pihole-FTL(main+0xdc) [0x561d0bf298ac]
[2020-05-31 06:11:26.725 882] B[0005]: 0x7fde6c6290b3, /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fde6c6290b3]
[2020-05-31 06:11:26.725 882] B[0006]: 0x561d0bf29a1a, /usr/bin/pihole-FTL(_start+0x2a) [0x561d0bf29a1a]
[2020-05-31 06:11:26.725 882] ------ Listing content of directory /dev/shm ------
[2020-05-31 06:11:26.725 882] File Mode User:Group  Filesize Filename
[2020-05-31 06:11:26.725 882] rwxrwxrwx root:root 280 .
[2020-05-31 06:11:26.725 882] rwxr-xr-x root:root 4K ..
[2020-05-31 06:11:26.725 882] rw------- pihole:pihole 4K FTL-per-client-regex
[2020-05-31 06:11:26.725 882] rw------- pihole:pihole 74K FTL-dns-cache
[2020-05-31 06:11:26.725 882] rw------- pihole:pihole 12K FTL-overTime
[2020-05-31 06:11:26.725 882] rw------- pihole:pihole 4M FTL-queries
[2020-05-31 06:11:26.725 882] rw------- pihole:pihole 4K FTL-upstreams
[2020-05-31 06:11:26.725 882] rw------- pihole:pihole 41K FTL-clients
[2020-05-31 06:11:26.725 882] rw------- pihole:pihole 98K FTL-domains
[2020-05-31 06:11:26.725 882] rw------- pihole:pihole 98K FTL-strings
[2020-05-31 06:11:26.725 882] rw------- pihole:pihole 12 FTL-settings
[2020-05-31 06:11:26.726 882] rw------- pihole:pihole 124 FTL-counters
[2020-05-31 06:11:26.726 882] rw------- pihole:pihole 48 FTL-lock
[2020-05-31 06:11:26.726 882] rwx------ root:root 80 multipath
[2020-05-31 06:11:26.726 882] ---------------------------------------------------
[2020-05-31 06:11:26.726 882] Thank you for helping us to improve our FTL engine!
[2020-05-31 06:11:26.726 882] FTL terminated!

**Comment by DL6ER** [comment] 2020-06-01 02:36
> `[2020-05-31 06:11:26.725 882] B[0003]: 0x561d0bf6d7bc, /usr/bin/pihole-FTL(main_dnsmasq+0x129c) [0x561d0bf6d7bc]`

This is a duplicate of https://github.com/pi-hole/FTL/issues/767. Your may find more information there. Getting some more debugging output would be helpful, check out the other issue ticket.

I'm going to close this one to avoid losing track of the individual discussions when we find a solution.

**Closed by DL6ER** 2020-06-01 02:36 UTC
