### ISSUE TITLE
Pihole is not installing update

### ISSUE THREAD

**Issue by philipp-buck** [pi-hole/FTL#1948] opened 2024-05-06 11:19 UTC
### Versions
pihole -v
Core
    Version is v5.17.3-336-g6ce747c9 (Latest: null)
    Branch is development-v6
    Hash is 6ce747c9 (Latest: 6ce747c9)
Web
    Version is v5.19-771-g78f59dda (Latest: null)
    Branch is development-v6
    Hash is 78f59dda (Latest: 78f59dda)
FTL
    Version is vDev-240a2fe (Latest: null)
    Branch is development-v6
    Hash is 240a2fe7 (Latest: e10bb5c6)

### Platform
Raspberry 3

cat /etc/os-release

PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Expected behavior

pihole show there is a FTP update available (which also the webpage claims) so a 
pihole -up 
should update to the new version

### Actual behavior / bug

pihole states everything is up2date

pihole -up
  [✓] Update local cache of available packages
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL binary already installed, verifying integrity...
  [i] Local binary up-to-date. No need to download!
  [i] FTL:		up to date
  [i] Warning: You are using FTL from a custom branch (development-v6) and might be missing future releases.

  [✓] Everything is up to date!

### Steps to reproduce

pihole -v
pihole -up

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment] 2024-05-06 15:58
**Using the command line:**
- use `pihole -d` command.
- when asked to upload the log, answer <kbd>Y</kbd>.
- copy only the token and paste here.

**Using the web interface:**
- click on _**Tools > Generate Debug Log**_ menu.
- then mark the second checkbox to upload the log and click on the big button.
- when finished, copy only the token and paste here.

**Comment by philipp-buck** [comment] 2024-05-06 16:48
https://tricorder.pi-hole.net/VTHJMsqB/

**Comment by rdwebdesign** [comment] 2024-05-06 17:31
Please, try `pihole updatechecker` followed by `pihole -v`.

If after that FTL version is still wrong, what is the output of `pihole-FTL -v`?

**Comment by philipp-buck** [comment] 2024-05-06 17:48
# pihole updatechecker

# pihole -v
Core
    Version is v5.17.3-336-g6ce747c9 (Latest: null)
    Branch is development-v6
    Hash is 6ce747c9 (Latest: 6ce747c9)
Web
    Version is v5.19-771-g78f59dda (Latest: null)
    Branch is development-v6
    Hash is 78f59dda (Latest: 78f59dda)
FTL
    Version is vDev-240a2fe (Latest: null)
    Branch is development-v6
    Hash is 240a2fe7 (Latest: e10bb5c6)

# pihole-FTL -v
vDev-240a2fe

**Comment by philipp-buck** [comment] 2024-05-08 10:21
Today pihole -up simply updated es expected ....
Core
    Version is v5.17.3-336-g6ce747c9 (Latest: null)
    Branch is development-v6
    Hash is 6ce747c9 (Latest: 6ce747c9)
Web
    Version is v5.19-773-ga2b2f60c (Latest: null)
    Branch is development-v6
    Hash is a2b2f60c (Latest: a2b2f60c)
FTL
    Version is vDev-e10bb5c (Latest: null)
    Branch is development-v6
    Hash is e10bb5c6 (Latest: e10bb5c6)
    
    I haven't changed anthing before running the update.

**Comment by rdwebdesign** [comment] 2024-05-08 15:53
Good to know it is fixed.

Maybe it was some temporary issue, but at the moment there is not much we can do to find out what was the cause.

I will close the issue for now, but if it happens again please report back.

**Closed by rdwebdesign** 2024-05-08 15:53 UTC
