### ISSUE TITLE
Seems pihole-FTL runs two threads and the second one also tries to start the dhcp server but cant as the port is already used:

### ISSUE THREAD

**Issue by Iridahonda** [pi-hole/FTL#301] opened 2018-06-05 07:47 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:** 

_5

**[BUG | ISSUE] Expected Behaviour:**

Minor bug - No error message in log

**[BUG | ISSUE] Actual Behaviour:**

All works as expected but systemclt  reports the error below.  I think something is wrong in the initialisation.  Nothing is using the port 67 before starting.

**[BUG | ISSUE] Steps to reproduce:**
systemctl restart pihole-FTL 
systemctl status pihole-FTL 

**Log file output [if available]**

Jun 09 07:54:52 raspberrypi systemd[1]: Starting LSB: pihole-FTL daemon...
Jun 09 07:54:52 raspberrypi pihole-FTL[4207]: Not running
Jun 09 07:54:52 raspberrypi su[4231]: Successful su for pihole by root
Jun 09 07:54:52 raspberrypi su[4231]: + ??? root:pihole
Jun 09 07:54:52 raspberrypi su[4231]: pam_unix(su:session): session opened for user pihole by (uid=0)
**Jun 09 07:54:52 raspberrypi pihole-FTL[4207]: dnsmasq: failed to bind DHCP server socket: Address already in use**
Jun 09 07:54:52 raspberrypi systemd[1]: Started LSB: pihole-FTL daemon.

**Device specifics**

Hardware Type: rPi, VPS, etc
OS:  Nas and rPi

**Comment by Iridahonda** [comment] 2018-06-05 07:49
Seems pihole-FTL (lastest build) runs with two threads but the second one gives and error during startup as it also tries to start the DHCP server and cant:

● pihole-FTL.service - LSB: pihole-FTL daemon
   Loaded: loaded (/etc/init.d/pihole-FTL; generated; vendor preset: enabled)
   Active: active (exited) since Tue 2018-06-05 09:10:11 CEST; 35min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 21825 ExecStop=/etc/init.d/pihole-FTL stop (code=exited, status=0/SUCCESS)
  Process: 21831 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/pihole-FTL.service

Jun 05 09:10:11 TimsNewMegaNas systemd[1]: Starting LSB: pihole-FTL daemon...
Jun 05 09:10:11 TimsNewMegaNas pihole-FTL[21831]: Not running
Jun 05 09:10:11 TimsNewMegaNas pihole-FTL[21831]: /etc/init.d/pihole-FTL: line 38: /sbin/resolvconf: No such file or dir
ectory
Jun 05 09:10:11 TimsNewMegaNas su[21853]: Successful su for pihole by root
Jun 05 09:10:11 TimsNewMegaNas su[21853]: + ??? root:pihole
Jun 05 09:10:11 TimsNewMegaNas su[21853]: pam_unix(su:session): session opened for user pihole by (uid=0)
**Jun 05 09:10:11 TimsNewMegaNas pihole-FTL[21831]: dnsmasq: failed to bind DHCP server socket: Address already in use**

**Comment by Mcat12** [comment] 2018-06-06 01:15
Please fill out the template. It really helps narrow down to find the solution.

Are you sure you don't have anything else using the port?

**Comment by Mcat12** [comment] 2018-07-27 03:00
@Iridahonda Can you reproduce this on the latest build? If so, make a new debug token.

**Comment by Iridahonda** [comment] 2018-07-27 05:34
Hi

Not sure which version you need testing. I’m running the bleeding edge branch from the weekend and it still does it.



Best regards

Tim
________________________________

**Comment by DL6ER** [comment] 2018-07-27 10:44
FTL can only use one thread to bind to DHCP addresses. So what you're seeing is likely a conflict with some other application who already bound to the socket before. This may be something else or maybe a second instance of FTL (which should not be there).

What's the output of
```
sudo ss -nlput
```
?

**Comment by Iridahonda** [comment] 2018-07-27 10:52
Ah think I have found the issue.

systemctl stop pihole-FTL does not kill pihole-FTL:

root@TimsNewMegaNas ~ # systemctl stop pihole-FTL
root@TimsNewMegaNas ~ # ps -A | grep pihole
17227 ?        00:00:00 pihole-FTL
17235 ?        00:00:00 pihole-FTL
root@TimsNewMegaNas ~ #


if I run

pkill pihole-FTL


root@TimsNewMegaNas ~ # pkill pihole-FTL
root@TimsNewMegaNas ~ # ps -A | grep pihole
root@TimsNewMegaNas ~ #


followed by:

systemctl start pihole-FTL

there is no issue.

Think there is an issue in /etc/init.d/pihole-FTL with the stop command.


Br

/T

**Comment by Mcat12** [comment] 2018-07-28 04:03
`resolvconf` is a dependency, and should be installed:
https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L197

Also, there have been updates since last weekend, so what was bleeding edge then is not bleeding edge now.

**Comment by Iridahonda** [comment] 2018-07-28 05:47
On Readynas boxes they use connman and resolvconf can’t be installed (not without messing things up at least)

Best regards

Tim
________________________________

**Comment by Mcat12** [comment] 2018-07-28 21:22
ReadyNAS appears to be based off of Debian Wheezy, and is heavily modified. We can not 100% support every modification of the platforms we support.

**Comment by lachlan-00** [comment] 2018-08-07 11:35
I just upgraded to 4 and i get this issue.

I'm running stretch and pihole-FTL steals port 53 from dnsmasq before it can start.
Then if you shut down FTL and start dnsmasq FTL will fail.

**Comment by DL6ER** [comment] 2018-08-31 11:11
Closing this issue as unrelated to Pi-hole FTL.

@Iridahonda is using an unsupported OS, @lachlan-00 had an unrelated issue as we don't use `dnsmasq` anymore.

**Closed by DL6ER** 2018-08-31 11:11 UTC
