### ISSUE TITLE
Bug: Certain IPV6 servers no longer work I.E. ::1.

### ISSUE THREAD

**Issue by jumpsmm7** [pi-hole/FTL#855] opened 2020-07-28 02:05 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---

**[BUG | ISSUE] Expected Behaviour:**
From what I can tell with my pihole, after updating to the version 5.1.1/5.1, I can no longer add certain dns servers. For example, I use to be able to use ::1#5354, now this is reported as incompatible. 

**[BUG | ISSUE] Actual Behaviour:**
Should accept use of ::1#5354 for forwarding purposes. 

**[BUG | ISSUE] Steps to reproduce:**
Try using address ::1#5453 as a custom ipv6 server. 
-
-
-
-

**Log file output [if available]**

`output`

**Device specifics**

Hardware Type: rPi, VPS, etc
OS: RPi4- latest Raspbian OS. 

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment] 2020-07-28 02:40
Use `127.0.0.1#5354`.

**Comment by yubiuser** [comment] 2020-07-28 05:26
Duplicate of https://github.com/pi-hole/AdminLTE/issues/1499

**Comment by jumpsmm7** [comment] 2020-07-28 08:18
My work around was adding a server instance to dnsmasq.d section. I technically dont need pihole menu to do that. I just thought this was worth mentioning for the pihole user space since it is technically an issue.

**Closed** 2020-07-28 08:19 UTC

**Comment by DL6ER** [comment] 2020-07-28 18:38
Thanks for taking the time to report this issue. @dschaper just mentioned an alternative and @yubiuser mentioned that there is already an open issue ticket for this.

As it is my fault of having been too busy in real life to look at this, so far.

Thank you for your report nonetheless, even when it is a duplicate ;-)

**Comment by PromoFaux** [comment] 2020-07-28 19:28
> As it is my fault of having been too busy in real life to look at this, so far.

If I'm not mistaken, it is already fixed in the next core release

**Comment by DL6ER** [comment] 2020-07-29 04:49
@PromoFaux thanks, it indeed looks like this. I checked the web code quickly and found
https://github.com/pi-hole/AdminLTE/blob/d8d3f316061ba60e0b1dfc6a11f6e917380aca5f/scripts/pi-hole/php/savesettings.php#L283-L313
which seems to handle ports correctly.

Have you tried adding said server through the dashboard after your changes or did you only test the CLI?
