### ISSUE TITLE
Issue with CAA queries, `pihole-ftl` takes 100% CPU and stays there, `dnsmasq` becomes unresponsive

### ISSUE THREAD

**Issue by flindeberg** [pi-hole/FTL#1100] opened 2021-04-10 12:32 UTC
### Versions

  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.4 (Latest: v5.4)
  FTL version is v5.7 (Latest: v5.7)

### Platform

- OS and version:  Raspberry Pi OS Buster

- Platform:  Raspberry Pi 3

### Expected behavior

That the DNS-query was successfully answered. I.e., at client:

```
> dig +short google.com CAA
0 issue "pki.goog"
```

### Actual behavior / bug

At client:

```
> dig +short google.com CAA
;; connection timed out; no servers could be reached
```

At the exact moment the query is received the `pihole-ftl` process spikes and `dnsmasq` stops responding. `pihole-ftl` process took one core fully and essentially locked the device down. No output in any `/var/log/pihole*.log` from that moment on. Note that the some combination of `dnsmasq` and `pihole-ftl` process is the culprit. `unbound` etc seemed to behave normally. 

In my setup I forward queries from `dnsmasq` to an `unbound`-instance. `dnsmasq` stopped responding, but `unbound` was still up and running.

### Steps to reproduce

After a reboot of the Raspberry I can no longer reproduce it. Prior to rebooting neither restart of dnsmasq nor ftl-suite helped long term, the first CAA-query after process restart always hung `pihole-ftl`. Prior to reboot any CAA query, such as `dig google.com CAA`, would instantly make `pihole-ftl` spike and make the resolver unresponsive. I reproduced the issue several times before I restarted the RPi itself. 

1. Let the device run for a year (?)
2. Try a CAA query, for example `dig google.com CAA`

As I cannot reproduce the issue it is not a very helpful bug-report. 

## Debug Token

- URL:  https://tricorder.pi-hole.net/wscp9kk4qz

### Additional context

Excerpts from log `pihole-FTL.log`;
```
[2021-04-09 06:59:00.767 452/T456] Notice: Database size is 2262.02 MB, deleted 3615 rows
[2021-04-09 07:05:20.729 452M] Resizing "FTL-strings" from 81920 to (86016 * 1) == 86016 (/dev/shm: 5.8MB\
 used, 225.5MB total, FTL uses 5.8MB)
[2021-04-09 08:00:00.862 452/T456] Notice: Database size is 2262.02 MB, deleted 4218 rows
[2021-04-09 08:23:40.462 452M] Resizing "FTL-dns-cache" from 57344 to (3840 * 16) == 61440 (/dev/shm: 5.8\
MB used, 225.5MB total, FTL uses 5.8MB)
[2021-04-09 08:49:14.914 13117M] ########## FTL started! ##########
[2021-04-09 08:49:14.915 13117M] FTL branch: master
[2021-04-09 08:49:14.915 13117M] FTL version: v5.7
[2021-04-09 08:49:14.915 13117M] FTL commit: 2999e2b5
[2021-04-09 08:49:14.916 13117M] FTL date: 2021-02-16 19:36:43 +0000
[2021-04-09 08:49:14.916 13117M] FTL user: pihole
```

```
Apr  9 08:29:15 dnsmasq[452]: cached YYY is NODATA-IPv6
Apr  9 08:29:16 dnsmasq[452]: query[A] ZZZ from 192.168.1.90
Apr  9 08:29:16 dnsmasq[452]: DHCP ZZZ is 192.168.1.70
Apr  9 08:29:17 dnsmasq[452]: query[CAA] XXX from 192.168.1.41
Apr  9 08:29:17 dnsmasq[452]: forwarded XXX to 127.0.0.1
Apr  9 08:49:22 dnsmasq[13119]: started, version pi-hole-2.84 cachesize 10000
Apr  9 08:49:22 dnsmasq[13119]: DNS service limited to local subnets
Apr  9 08:49:22 dnsmasq[13119]: compile time options: IPv6 GNU-getopt no-DBus no-UBus no-i18n IDN DHCP DH\
CPv6 Lua TFTP no-conntrack ipset auth cryptohash DNSSEC loop-detect inotify dumpfile
Apr  9 08:49:22 dnsmasq[13119]: DNSSEC validation enabled
```

The first crash was at around 08:30, and then I did the first process restart at 08:49. In the logs above YYY is an external host name. ZZZ is a local name with a static IP / DHCP-config. XXX is the domain I asked for the CAA-resource-record from.

**Comment by DL6ER** [comment] 2021-04-10 12:58
Yes, this will be a tricky one because the hanging will very likey have happened in dnsmasq code (FTL doesn't really care about the requested type). I'll nevertheless try to reproduce this too, even when I don't have a system running non-stop for a year ;-)

**Comment by flindeberg** [comment] 2021-04-10 13:40
Just holler if there is anything I can provide! @DL6ER 

I'll probably try flooding the server a bit tonight or tmrw and see if that can help cause the issue. I wonder if the `Notice: Database size is 2262.02 MB, deleted 3615 rows` has anything to do with the issue.

**Comment by DL6ER** [comment] 2021-04-13 10:05
I'm closing this because it seems very unlikely that we'll be able to reproduce this anytime soon. If it happens again, please check a process monitor (like `htop`) for which part of FTL takes the entire core to 100%.

Also, please follow the instructions at https://docs.pi-hole.net/ftldns/debugging/ However, instead of issuing `continue` jump right away to `backtrace` so we can get a better view of where we are.

Then, issue `info threads` which will list how many threads are there. Copy&paste the output of this and switch to each thread individually using `thread 1`, `thread 2`, etc. For each thread, run `backtrace` again.

Only when we have this we may be able to do something about it. Sorry for not having better news for you...

**Closed by DL6ER** 2021-04-13 10:05 UTC
