### ISSUE TITLE
FTL is offline after restarting pihole.

### ISSUE THREAD

**Issue by richardtempleman** [pi-hole/FTL#145] opened 2017-10-08 14:37 UTC
[x] In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

1
---
I am a newbie to pihole and have just installed pihole on ubuntu 16.04

Fault:  Dashboard showing zero stats.

Checked the FTL log and this shows FTL crashed

-

**Log file output [if available]**
Here is the requested part of the log file

2017-10-08 15:27:55.271] ########## FTL started! ##########
[2017-10-08 15:27:55.271] FTL branch: (no branch)
[2017-10-08 15:27:55.271] FTL hash: v2.11
[2017-10-08 15:27:55.271] FTL date: 2017-09-28 11:01:31 -0700
[2017-10-08 15:27:55.271] FTL user: pihole
[2017-10-08 15:27:55.271] Notice: Found no readable FTL config file
[2017-10-08 15:27:55.271]         Using default settings
[2017-10-08 15:27:55.271] Starting config file parsing
[2017-10-08 15:27:55.271]    SOCKET_LISTENING: only local
[2017-10-08 15:27:55.271]    TIMEFRAME: Rolling 24h
[2017-10-08 15:27:55.271]    QUERY_DISPLAY: Show queries
[2017-10-08 15:27:55.271]    AAAA_QUERY_ANALYSIS: Show AAAA queries
[2017-10-08 15:27:55.271]    MAXDBDAYS: max age for stored queries is 365 days
[2017-10-08 15:27:55.271] Finished config file parsing
[2017-10-08 15:27:55.273] Found no other running pihole-FTL process
[2017-10-08 15:27:55.274] PID of FTL process: 16210
[2017-10-08 15:27:55.299] Gravity list entries: 111579
[2017-10-08 15:27:55.299] No blacklist present
[2017-10-08 15:27:55.299] No wildcard blocking list present
[2017-10-08 15:27:55.299] Database initialized
[2017-10-08 15:27:55.299] Starting initial log file parsing
[2017-10-08 15:27:55.299] Reading from /var/log/pihole.log.1 (rw-r--r--)
[2017-10-08 15:27:55.299] Notice: Increasing forwarded struct size from 0 to 4 (188.00 B)
[2017-10-08 15:27:55.300] New forward server: 8.8.4.4 google-public-dns-b.google.com (0/4)
[2017-10-08 15:27:55.300] Notice: Increasing overTime struct size from 0 to 100 (4.23 KB)
[2017-10-08 15:27:55.301] New forward server: 8.8.8.8 google-public-dns-a.google.com (1/4)
[2017-10-08 15:27:55.301] Notice: Increasing queries struct size from 0 to 10000 (324.28 KB)
[2017-10-08 15:27:55.301] Notice: Increasing domains struct size from 0 to 1000 (356.28 KB)
[2017-10-08 15:27:55.301] Notice: Increasing clients struct size from 0 to 10 (356.53 KB)
[2017-10-08 15:27:55.301] New client: 127.0.0.1 localhost (0/10)
[2017-10-08 15:27:55.301] FATAL ERROR: Trying to access overTime[-1], but maximum is 100
[2017-10-08 15:27:55.301]              found in process_pihole_log() (line 363) in parser.c
[2017-10-08 15:27:55.301] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2017-10-08 15:27:55.301] ---------------------------->  FTL crashed!  <----------------------------
[2017-10-08 15:27:55.301] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2017-10-08 15:27:55.301] Please report a bug at https://github.com/pi-hole/FTL/issues
[2017-10-08 15:27:55.301] and include in your report already the following details:

[2017-10-08 15:27:55.301] FTL has been running for 0 seconds
[2017-10-08 15:27:55.301] FTL branch: (no branch)
[2017-10-08 15:27:55.301] FTL hash: v2.11
[2017-10-08 15:27:55.301] FTL date: 2017-09-28 11:01:31 -0700
[2017-10-08 15:27:55.301] FTL user: pihole
[2017-10-08 15:27:55.301]
Received signal: Segmentation fault
[2017-10-08 15:27:55.301]      at address: 4017
[2017-10-08 15:27:55.301]       with code: SEGV_MAPERR (Address not mapped to object)
[2017-10-08 15:27:55.301] Memory usage (structs): 356428
[2017-10-08 15:27:55.301] Memory usage (dynamic): 310

[2017-10-08 15:27:55.301] Thank you for helping us to improve our FTL engine!
[2017-10-08 15:27:55.301] FTL terminated!

**Device specifics**

Hardware Type: PC running ubuntu 16.04   (dual boot with Windows 8.1)
OS: 

I am running pihole locally (not VPN) and changed the router DNS settings to point to  192.168.1.2 (my fixed IP addr.   As an aside, is this feasible?

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment] 2017-10-08 14:48
Please provide us with more details. The template is there for a reason.....

**Comment by richardtempleman** [comment] 2017-10-08 14:50
Updated the template now, you were too quick for me, this is the first time I have used this.

**Comment by richardtempleman** [comment] 2017-10-08 15:12
Apologies.  I have updated the thread now.

________________________________

**Comment by DL6ER** [comment] 2017-10-08 15:33
Thanks for your report. The issue you are seeing is known (we call it the "time traveler" issues). This issue will be resolved by FTL v2.11.1 which is sheduled to released very soon (see https://github.com/pi-hole/FTL/pull/144)

We currently think that the issue comes from daylight saving time issues where the computer clock jumped backwards by one hour at once. Can you confirm that this was the case for you today?

**Comment by richardtempleman** [comment] 2017-10-08 15:43
There was no time change on my PC.  BST here in the UK doesn't change until the end of October.

**Comment by Mcat12** [comment] 2017-10-08 15:50
Can you provide the a snippet of the Pi-hole log when FTL crashed? (`/var/log/pihole.log`)

**Comment by DL6ER** [comment] 2017-10-08 16:30
If you want us to analyze the cause of your crash, please run
```
cat /var/log/pihole.log | pihole tricorder
cat /var/log/pihole.log.1 | pihole tricorder
```
and provide us with the generated tokens. Note that we ([the developers](github.com/orgs/pi-hole/teams/debug/members)) will be the only ones to see your uploaded logs. If you don't want to do this (e.g. due to privacy concerns), then we understand that, of course.

To resolve your issue you can either wait for the update of `FTL` to be released, so run `pihole -f` (maybe twice). This will clear the logs which contain the problematic jump in time . `FTL` should then work as expected again.

**Comment by richardtempleman** [comment] 2017-10-08 18:00
Tokens:
wot2f71tvu
iadi2x6qxp

**Comment by DL6ER** [comment] 2017-10-08 18:38
Thank for providing the necessary details to debug your specific scenario.
In your `pihole.log.1` file the backwards jump in time can be found already at the very beginning of the file:
<pre>
[...]
Oct  7 17:16:55 dnsmasq[1330]: query[AAAA] <b>ntp.ubuntu.com</b> from 127.0.0.1
Oct  7 17:16:55 dnsmasq[1330]: forwarded ntp.ubuntu.com to [...]
Oct  7 <b>17:16:55</b> dnsmasq[1330]: reply ntp.ubuntu.com is [...]
Oct  7 <b>16:17:16</b> dnsmasq[1330]: query[A] [...].com from [...]
Oct  7 16:17:16 dnsmasq[1330]: forwarded [...].com to [...]
[...]
</pre>

As you can see, your device queried the Ubuntu time server 19 seconds after `dnsmasq` is started. This has the consequence that the local clock gets adjusted by an entire hour backwards. So, although you mention that it isn't a daylight saving time issue, it at least exactly looks like one. I'm unsure about the cause of this ... are you running an a machine that has no on-board realtime clock (RTC)? To keep costs low and the size small, an RTC is not included with e.g. the Raspberry Pi.

**Comment by DL6ER** [comment] 2017-10-08 18:38
Note: The fix we coded earlier will resolve the issue you are seeing, although it is still unclear why your local clock was off be one hour.

**Comment by richardtempleman** [comment] 2017-10-08 19:49
Thanks so much for isolating the cause of the problem!   I will look into my ubuntu configuration regarding the time settings.   
I will wait until the next release of Pihole-FT which contains the fix and then try again.
Thanks again for all your efforts.
Richard

**Comment by richardtempleman** [comment] 2017-10-09 11:49
Great - the fix worked!!
Pihole web interface is working perfectly.
I shall definitely make a donation

**Comment by richardtempleman** [comment] 2017-10-09 11:52
Great - your fix worked!!!
I wish all software could be updated so quickly and efficiently.
I am very impressed and will make a donation ASAP.
Thank you so much DL6ER once again.
Richard

**Closed** 2017-10-09 14:51 UTC
Labels: Bug, Fixed in next release
