### ISSUE TITLE
FTL will not install

### ISSUE THREAD

**Issue by RickvLeeuwen** [pi-hole/FTL#400] opened 2018-10-21 12:22 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**Maybe related to the update issue: https://github.com/pi-hole/FTL/issues/365**

**How familiar are you with the codebase?:**

2

---

**[BUG] Expected Behaviour:**
Installing FTL

**[BUG] Actual Behaviour:**
[i] FTL Checks...
  [✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [✗] Downloading and Installing FTL
  **Error: Unable to get latest release location from GitHub**
  [✗] FTL Engine not installed

**[BUG] Steps to reproduce:**
Installed fresh and latest raspbian lite
Ran curl -sSL https://install.pi-hole.net | bash

**Log file output [if available]**

[i] FTL Checks...
  [✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [✗] Downloading and Installing FTL
  **Error: Unable to get latest release location from GitHub**
  [✗] FTL Engine not installed

**Device specifics**
RPi 3
Fresh installed latest rasbian lite

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment] 2018-10-21 15:37
This is related to/a duplicate of #365, and is a Core issue instead of an FTL issue. It should be fixed in dev.

**Closed by Mcat12** 2018-10-21 15:37 UTC
