### ISSUE TITLE
missing url

### ISSUE THREAD

**Issue by deepgray** [pi-hole/FTL#365] opened 2018-08-22 03:12 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{1}_

---

**[BUG | ISSUE] Expected Behaviour:**
pihole -up attempts to get a URL that doesn't exist.

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

- pihole -up from root prompt
-
-
-

**Log file output [if available]**

root@pi-hole:~# pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] FTL:		update available

  [i] FTL out of date

  [i] FTL Checks...
  [i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404 Not Found
  [✗] Downloading and Installing FTL
  Error: URL not found
root@pi-hole:~# 

**Device specifics**

Hardware Type: rPi
OS:
Linux pi-hole.local 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Andrea-Tabbles** [comment] 2018-08-22 15:55
I have thee same,

**Comment by morbidxbean** [comment] 2018-08-27 02:40
+1

**Comment by StackKorora** [comment] 2018-08-29 01:56
Same
```
$ bash -x  /opt/pihole/update.sh
[snip - cutting to the end where it matters ]
+ local 'str=Downloading and Installing FTL'
+ echo -ne '  [i] Downloading and Installing FTL...'
  [i] Downloading and Installing FTL...++ curl -sI https://github.com/pi-hole/FTL/releases/latest
++ grep Location
++ awk -F / '{print $NF}'
+ latesttag=$'v4.0\r'
 == v* ]].0
++ mktemp -d
+ pushd /tmp/tmp.Vw7h9OTxkn
+ install -T -m 0755 /etc/.pihole/advanced/Templates/pihole-FTL.service /etc/init.d/pihole-FTL
+ local ftlBranch
+ local url
+ [[ -f /etc/pihole/ftlbranch ]]
+ ftlBranch=master
+ [[ master == \m\a\s\t\e\r ]]
+ url=https://github.com/pi-hole/FTL/releases/download/v4.0
+ curl -sSL --fail https://github.com/pi-hole/FTL/releases/download/v4.0/ -o ''
curl: (22) The requested URL returned error: 404 Not Found
+ popd
+ echo -e '\r  [✗] Downloading and Installing FTL'
  [✗] Downloading and Installing FTL
+ echo -e '  Error: URL not found'
  Error: URL not found
+ return 1
+ return 1
```

**Comment by mgalde** [comment] 2018-08-29 02:11
I have the same issue, FTL reported 404, file Not Found

I ran pihole -r and completed a repair process

FTL is now updated and running pihole -up then updates the web interface correctly

**Comment by StackKorora** [comment] 2018-08-29 02:27
Thanks @mgalde, that pointed me to the problem. I found another issue that I will open in another ticket.

I can confirm that after the repair the update worked fine.

**Comment by StackKorora** [comment] 2018-08-29 02:29
Also, in case anyone cares about this actual bug....
I traced the problem to the FTLinstall function in the file '/etc/.pihole/automated install/basic-install.sh' where the "binary" variable was empty because it was empty in the FTLdetect function! I didn't figure out why before I tried the solution above.

**Comment by XGhozt00** [comment] 2018-09-11 00:05
Same problem.
https://github.com/pi-hole/FTL/issues/229#issuecomment-414271363

**Comment by bitchecker** [comment] 2018-09-14 18:38
same problem.
running `pihole -r` as suggested from @mgalde, and re-run `pihole -up` i see the same error:

```
+ url=https://github.com/pi-hole/FTL/releases/download/v4.0
+ curl -sSL --fail https://github.com/pi-hole/FTL/releases/download/v4.0/ -o ''
curl: (22) The requested URL returned error: 404 Not Found
+ popd
+ echo -e '\r  [✗] Downloading and Installing FTL'
[✗] Downloading and Installing FTL
+ echo -e '  Error: URL not found'
Error: URL not found
+ return 1
+ return 1
```

**Comment by Mcat12** [comment] 2018-09-14 20:12
Try using an external DNS server in `/etc/resolv.conf` and then `pihole -r`

**Comment by bitchecker** [comment] 2018-09-14 20:21
@Mcat12, DNS are already differen because they are those that are used by dnsmasq to forward non-blocked requests.

**Comment by bitchecker** [comment] 2018-10-12 20:57
so, there's any news about?

**Comment by Mcat12** [comment] 2018-10-13 01:59
Did you follow the instructions I gave you?

**Comment by bitchecker** [comment] 2018-10-13 08:51
Seriously, did you read my fast reply on your message?

**Comment by bitchecker** [comment] 2018-10-14 08:45
@Mcat12 this is the debug token: `a7x8vhfjlf`.

i see the same problem that gives update process also into debug tool...when it tries to `dig` a domain, that domain seems to be a null variable.

**Comment by lloyda** [comment] 2018-10-14 11:00
I've just had the same issue, and as stated higher up, the binary variable was never being set as a result of get_binary_name never being called.  Added a call to this in FTLinstall, and all now working.

**Comment by bitchecker** [comment] 2018-10-16 20:03
@lloyda so, it will be fixed?

**Comment by Mcat12** [comment] 2018-10-17 04:15
It will be fixed for the next release.

You can also try download FTL directly to `/usr/bin/pihole-FTL` from https://ftl.pi-hole.net/v4.0/

**Closed** 2018-12-09 21:38 UTC
Labels: Fixed in next release

**Comment by bitchecker** [comment] 2018-12-11 19:00
@Mcat12 i've got the same problem also downloading new `pihole-FTL` from URL.

**Comment by Mcat12** [comment] 2018-12-11 21:59
Please make a new issue, this one is closed.
