### ISSUE TITLE
FTL crashed - Segmentation fault at address: 0x18 with code: SEGV_MAPERR (Address not mapped to object)

### ISSUE THREAD

**Issue by rodebike** [pi-hole/FTL#835] opened 2020-07-16 00:48 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_{1}_

---

**[BUG | ISSUE] Expected Behaviour:**
FTL should run!

**[BUG | ISSUE] Actual Behaviour:**
FTL crashed!

**[BUG | ISSUE] Steps to reproduce:**

Updated to v5.1, it (FTL) crashed, updated to v5.1.1 it (FTL) also crashed.

**Log file output [if available]**

*** [ INITIALIZING ]
[i] 2020-07-15:19:20:02 debug log has been initialized.

*** [ INITIALIZING ] Sourcing setup variables
[i] Sourcing /etc/pihole/setupVars.conf...

*** [ DIAGNOSING ]: Core version
[i] Core: v5.1.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Remotes: origin	https://github.com/pi-hole/pi-hole.git (fetch)
             origin	https://github.com/pi-hole/pi-hole.git (push)
[i] Branch: master
[i] Commit: v5.1.1-0-g56cd7c4

*** [ DIAGNOSING ]: Web version
[i] Web: v5.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Remotes: origin	https://github.com/pi-hole/AdminLTE.git (fetch)
             origin	https://github.com/pi-hole/AdminLTE.git (push)
[i] Branch: master
[i] Commit: v5.1-0-gd8d3f316

*** [ DIAGNOSING ]: FTL version
[✓] FTL: v5.1

*** [ DIAGNOSING ]: lighttpd version
[i] 1.4.45

*** [ DIAGNOSING ]: php version
[i] 7.0.33

**Edit** Removed most of the debug log

**Device specifics**

Hardware Type: Raspberry Pi Zero Rev 1.1
OS: Raspbian   GNU/Linux 9 (stretch)
--

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PureFallen** [comment] 2020-07-16 01:22
`* The debug log can be uploaded to tricorder.pi-hole.net for sharing with developers only.`
I would recommend you to do that because of all the information inside the log that could in worse case used against you since it is public accessable on Github for everyone now, but thats a different topic.

The issue seems to hit people "by random". I seem to be affected as well, so do a [handful of people in Socialmedia](https://www.reddit.com/r/pihole/comments/hrwq5q/pihole_51_released/fy6wo2q/).
So we are atleast no alone with the problem, but that doesn't really explain how it happened and how to fix it either.

**Comment by DL6ER** [comment] 2020-07-16 04:22
> [2020-07-15 16:49:01.847 571] FTL version: v5.0

Please update to v5.1 which contains an important big fix for the embedded DNS resolver.

@PureFallen more info, please (ideally in a separate issue ticket). The link just says that Chronometer reports a wrong status, nothing about a crash. This is known since yesterday. This script hasn't been updated in almost 3 years and is yet to be updated. Sorry that we missed this for now.

**Comment by PureFallen** [comment] 2020-07-16 12:47
> @PureFallen more info, please (ideally in a separate issue ticket). The link just says that Chronometer reports a wrong status, nothing about a crash. This is known since yesterday. This script hasn't been updated in almost 3 years and is yet to be updated. Sorry that we missed this for now.

Yeah, bad timing and investigation from my side here. Seems like the both errors aren't connected, managed to get FTL back running using `pihole -r`.
The seperate issue ticket for chronometer/PADD no longer being able to receive the information from FTL does now exist.

**Comment by DL6ER** [comment] 2020-07-17 09:32
Thanks, I will close this issue ticket as I'm fairly sure the update fixed the cause of the crash. If the issue persists, re-open or create a new ticket, whatever seems most appropriate for you at that point.

Thanks for using the Pi-hole and your feedback!

**Closed by DL6ER** 2020-07-17 09:32 UTC
