### ISSUE TITLE
Pi-Hole FTL crashes at 450+ clients as soon as clients FTL box displayed

### ISSUE THREAD

**Issue by grobbins-watco** [pi-hole/FTL#231] opened 2018-02-15 21:09 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

1
---

**[BUG | ISSUE] Expected Behaviour:**
NO

**[BUG | ISSUE] Actual Behaviour:**
FTL crashes

**[BUG | ISSUE] Steps to reproduce:**

Once more than 450 clients are on the Pi-Hole, if you logoff or log back on, FTL crashes as soon as "Clients" box is displayed. Restarting FTL (service pihole-FTL restart) will crash FTL again as soon as "Clients" box is displayed again. System has run for 48hrs with no issues once logged out and FTL works until logged in again.

-
-
-

**Log file output [if available]**

[2018-02-15 14:46:31.622] Finished initial log file parsing
[2018-02-15 14:46:31.622]  -> Total DNS queries: 530346
[2018-02-15 14:46:31.622]  -> Cached DNS queries: 294722
[2018-02-15 14:46:31.622]  -> Blocked DNS queries: 66387
[2018-02-15 14:46:31.622]  -> Unknown DNS queries: 0
[2018-02-15 14:46:31.622]  -> Unique domains: 18480
[2018-02-15 14:46:31.622]  -> Unique clients: 473
[2018-02-15 14:46:31.622] Successfully accessed setupVars.conf
[2018-02-15 14:46:31.622] Listening on port 4711 for incoming connections
[2018-02-15 14:49:54.554] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2018-02-15 14:49:54.554] ---------------------------->  FTL crashed!  <----------------------------
[2018-02-15 14:49:54.554] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2018-02-15 14:49:54.554] Please report a bug at https://github.com/pi-hole/FTL/issues
[2018-02-15 14:49:54.554] and include in your report already the following details:

[2018-02-15 14:49:54.554] FTL has been running for 217 seconds
[2018-02-15 14:49:54.554] FTL branch: v2.13.2
[2018-02-15 14:49:54.554] FTL version: v2.13.2
[2018-02-15 14:49:54.554] FTL commit: 1de2b99c8a812d4d2dbe6b1e4644e20a4b14bb1e
[2018-02-15 14:49:54.554] FTL date: 2018-01-07 17:34:24 -0800
[2018-02-15 14:49:54.554] FTL user: pihole
[2018-02-15 14:49:54.554]
Received signal: Segmentation fault
[2018-02-15 14:49:54.554]      at address: 0
[2018-02-15 14:49:54.555]       with code: Unknown (128),
[2018-02-15 14:49:54.555] Memory usage (structs): 17917444
[2018-02-15 14:49:54.555] Memory usage (dynamic): 472203

[2018-02-15 14:49:54.555] Thank you for helping us to improve our FTL engine!
[2018-02-15 14:49:54.555] FTL terminated!

**Device specifics**

Hardware Type: rPi, VPS, etc
OS:
Pi-Hole install from curl -sSL https:\\install.pi-hole.net|bash method

Running on VM Ware virtual machine running Debian Jessie, 4vCPU, 2GB RAM, 16GB HD

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment] 2018-02-16 05:49
This is a known issue with `v2.13.2`. If you cannot update to `v3.0` (as you are running Debian Jessie), you can check out a branch of FTL where we backported this fix. Run
```
sudo pihole checkout ftl master-fix/ssend
```

**Comment by DL6ER** [comment] 2018-03-30 20:57
Closing due to non-responsiveness of original poster and since I posted a confirmed working solution.

**Closed by DL6ER** 2018-03-30 20:57 UTC
