### ISSUE TITLE
pihole-FTL unable to reisze shared memory at create_shm()

### ISSUE THREAD

**Issue by trupf** [pi-hole/FTL#977] opened 2020-12-13 12:33 UTC
### Versions

- Pi-hole:  v5.2.1
- AdminLTE:  v5.2.1
- FTL:  v5.3.2-dirty

### Platform

- OS and version:  Debian 10

- Platform:  Zyxel NAS, armv7l

### Expected behavior

pihole-FTL should start without error.

### Actual behavior / bug

pihole-FTL stops with error: 
FATAL: create_shm(): Failed to resize "FTL-lock" (4) to 28: Operation not supported (-1)

### Steps to reproduce
just normal startup of the service

not relevant

## Debug Token
not needed

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context
[shmem_falloc_5.3.2.tar.gz](https://github.com/pi-hole/FTL/files/5684561/shmem_falloc_5.3.2.tar.gz)
Problem seems to be my ancient kernel, which doesn't reply with the expected result to the fallocate() system function call (may be this function call is not even supported). Unfortunately I can not update as there is no newer kernel available for my hardware. 
Since pihole-FTL v5.2 was working without issues, I checked the difference and found that ftruncate() is used there instead of fallocate() in shmem.c. The attached path does revert the change and now pihole-FTL is working for me. Could you check if using ftruncate() instead of fallocate() would be possible for future pihole-FTL versions?

**Comment by DL6ER** [comment] 2020-12-14 06:25
> Could you check if using `ftruncate()` instead of `fallocate()` would be possible for future pihole-FTL versions?

No, unfortunately, it is not. The difference between the two is subtitle, but, simplified and in a nutshell, it is that `ftruntace()` only "announces" that we want some amount of memory, while `fallocate()` really takes the memory. This change of ours fixed several issues where systems were short on memory and other processes were able to "steal" it from us. The result was a crash because FTL (rightfully) assumed it had the required memory available However, when it was stolen, it simply crashed when trying to access memory which was allocated by another process in the meantime. `fallocate` guarantees that the memory is ours.

What we could do is catching the `Operation not supported` and retrying with `ftruncate()` in this case. Together with a warning that this is a fall-back and may lead to issues when you're short on memory. What do you think about this solution?

**Comment by JuergenBausa** [comment] 2020-12-14 17:27
I have the same problem as the original poster. As the hardware seems simsilar, it could be based on the same root cause.

I try to run pihole-FTL v5.3.2 on a Zyxel NSA310 NAS inside a debian chroot environment running wheezy. I know that wheezy is not officially supported but so far I could solve all problems. The Zyxel NAS still runs kernel 2.6.31.8 which I cannot change (the box is out of support).

This is the mesage I get:

[2020-12-14 17:08:34.295 8642M] Finished config file parsing
[2020-12-14 17:08:34.296 8642M] Creating shared memory with name "FTL-lock" and size 28 (/dev/shm: 0.0B used, 127.0MB total)
[2020-12-14 17:08:34.296 8642M] FATAL: create_shm(): Failed to resize "FTL-lock" (4) to 28: Operation not supported (-1)

Your proposal (retrying with ftruncate) seems to me very promising. I would like to test it on my system.

Juergen

**Comment by trupf** [comment] 2020-12-14 20:42
> What we could do is catching the `Operation not supported` and retrying with `ftruncate()` in this case. Together with a warning that this is a fall-back and may lead to issues when you're short on memory. What do you think about this solution?

That sounds great to me.

**Comment by DL6ER** [comment] 2020-12-17 11:16
@trupf @JuergenBausa Could you check out the new branch `tweak/fallback_ftruncate` and see if this fixes it for you?

**Comment by JuergenBausa** [comment] 2020-12-17 12:06
How do I check this version out? Is it

`pihole ftl checkout tweak/fallback_ftruncate`

**Comment by DL6ER** [comment] 2020-12-17 12:53
Oh, yes, almost. If you're running the binary pre-compiled, use
```
pihole checkout ftl tweak/fallback_ftruncate
```

I guessed you'd both compile if from source because @trupf submitted a patch, but I see now that this isn't true.

**Comment by trupf** [comment] 2020-12-17 15:56
I have compiled the source, it is running and working. In the log file I now get the failure notice and a warning fro every resizing operation:

```
[2020-12-17 16:49:28.027 28148M] Finished config file parsing
[2020-12-17 16:49:28.027 28148M] INFO: create_shm(): Failed to allocate 28 bytes for "FTL-lock" (Operation not supported, 95), space has only been reserved.
[2020-12-17 16:49:28.027 28148M] Creating mutex
[2020-12-17 16:49:28.028 28148M] INFO: create_shm(): Failed to allocate 152 bytes for "FTL-counters" (Operation not supported, 95), space has only been reserved.
[2020-12-17 16:49:28.028 28148M] INFO: create_shm(): Failed to allocate 12 bytes for "FTL-settings" (Operation not supported, 95), space has only been reserved.
[2020-12-17 16:49:28.028 28148M] INFO: create_shm(): Failed to allocate 4096 bytes for "FTL-strings" (Operation not supported, 95), space has only been reserved.
[2020-12-17 16:49:28.028 28148M] INFO: create_shm(): Failed to allocate 65536 bytes for "FTL-domains" (Operation not supported, 95), space has only been reserved.
[2020-12-17 16:49:28.028 28148M] INFO: create_shm(): Failed to allocate 339968 bytes for "FTL-clients" (Operation not supported, 95), space has only been reserved.
[2020-12-17 16:49:28.028 28148M] INFO: create_shm(): Failed to allocate 28672 bytes for "FTL-upstreams" (Operation not supported, 95), space has only been reserved.
[2020-12-17 16:49:28.028 28148M] INFO: create_shm(): Failed to allocate 229376 bytes for "FTL-queries" (Operation not supported, 95), space has only been reserved.
[2020-12-17 16:49:28.028 28148M] INFO: create_shm(): Failed to allocate 20480 bytes for "FTL-overTime" (Operation not supported, 95), space has only been reserved.
[2020-12-17 16:49:28.029 28148M] INFO: create_shm(): Failed to allocate 4096 bytes for "FTL-dns-cache" (Operation not supported, 95), space has only been reserved.
[2020-12-17 16:49:28.029 28148M] INFO: create_shm(): Failed to allocate 4096 bytes for "FTL-per-client-regex" (Operation not supported, 95), space has only been reserved.
[2020-12-17 16:49:28.031 28148M] Database version is 9
```
and so on.
Thanks for your help.

**Comment by DL6ER** [comment] 2020-12-18 07:49
The change has been merged into `development` and will be included in the next release.

**Comment by JuergenBausa** [comment] 2020-12-18 12:27
I also tried now the patched version and I get the same output as trupf. Seems to work now. Thank you!

**Comment by DL6ER** [comment] 2020-12-20 10:02
@trupf @JuergenBausa Could you please verify if
```
pihole checkout ftl tweak/interruptsafe_systemcalls
```
works for you as well? If so, it'll be a better fix than #984 because it uses `posix_fallocate` which is hopefully more portable. It is also more robust because it actually allocates the memory.

I checked the generated assembler code and on a modern kernel it is just the same as `fallocate()` :heavy_check_mark: 
On older kernels (or file systems that do not support this), it does call `fstat()` to set the larger file size and then writes one zero to the beginning of each new block in the file.

This should allow us to use a common function for all kernels that does not need any fallback. Any feedback from you will be highly appreciated.

**Comment by JuergenBausa** [comment] 2020-12-20 11:13
Yes, tweak/interruptsafe_systemcalls works also. At least I get no error message. I am still in the process of configuring pihole and fitting it to my existing server and its services. So I cant say anything about the function for a longer period.

**Comment by DL6ER** [comment] 2020-12-20 11:28
Thanks for your report. The critical part here was : Does it start or does it fail like initially reported in this issue ticket. Since it starts, I will revert #984 because it will be solved more elegantly with `tweak/interruptsafe_systemcalls`. Thie most important benefit is that 
> a warning that this is a fall-back and may lead to issues when you're short on memory

isn't necessary any longer as the new method ensures that issues when being short on memory don't happen.

**Comment by trupf** [comment] 2020-12-20 13:50
yes tweak/interruptsafe_systemcalls works for me as well.

**Comment by DL6ER** [comment] 2020-12-24 11:19
The next version of FTL has been released. It contains the discussed fix.

If you have switched branches using the `checkout` command, please update and run
```
pihole checkout master
```
to get back on-track. Thanks for helping us to make Pi-hole better for us all!

If you have any issues, please either reopen this ticket or (preferably) create a new ticket describing the issues in further detail and only reference this ticket. This will help us to help you best.

**Closed by DL6ER** 2020-12-24 11:19 UTC
Labels: Fixed in next release
