### ISSUE TITLE
FTL crashing after a few hours

### ISSUE THREAD

**Issue by riddlecp** [pi-hole/FTL#1399] opened 2022-08-12 20:25 UTC
### Versions

- Pi-hole:  v5.11.4
- AdminLTE:  v5.13
- FTL:  v5.16.1

### Platform

- OS and version:  Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi

### Expected behavior

I expect pihole to run for multiple weeks/months correctly instead of a few hours at a time

### Actual behavior / bug

FTL crashes and all DNS resolution stops

### Steps to reproduce

Nothing, it just happens in the background after working fine for a few hours

## Debug Token
  pihole -d hangs at "*** [ DIAGNOSING ]: Dashboard and block page"
- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

[2022-08-12 13:28:04.756 5096M] Reloading DNS cache
[2022-08-12 13:28:04.851 5096/T5100] SQLite3 message: file renamed while open: /etc/pihole/gravity.db (28)
[2022-08-12 13:28:04.858 5096/T5100] Compiled 0 whitelist and 0 blacklist regex filters for 3 clients in 1.7 msec
[2022-08-12 13:28:04.858 5096/T5100] Blocking status is enabled
[2022-08-12 13:30:00.149 5096/T5100] Notice: Database size is 670.36 MB, deleted 540 rows
[2022-08-12 13:38:52.412 5096M] Resizing "FTL-dns-cache" from 4096 to (512 * 16) == 8192 (/dev/shm: 1.3MB used, 484.0MB total, FTL uses 1.3MB)
[2022-08-12 13:39:00.159 5096/T5100] Notice: Database size is 670.36 MB, deleted 59 rows
[2022-08-12 13:44:34.732 5096/T11949] WARN: Could not write() everything in ssend() [/__w/FTL/FTL/src/api/socket.c:245]: Connection reset by peer
[2022-08-12 13:50:00.160 5096/T5100] Notice: Database size is 670.36 MB, deleted 34 rows
[2022-08-12 14:00:00.107 5096/T5100] Notice: Database size is 670.36 MB, deleted 34 rows
[2022-08-12 14:10:00.088 5096/T5100] Notice: Database size is 670.36 MB, deleted 30 rows
[2022-08-12 14:20:00.140 5096/T5100] Notice: Database size is 670.36 MB, deleted 40 rows
[2022-08-12 14:30:00.095 5096/T5100] Notice: Database size is 670.36 MB, deleted 46 rows
[2022-08-12 14:40:00.152 5096/T5100] Notice: Database size is 670.36 MB, deleted 68 rows
[2022-08-12 14:50:00.068 5096/T5100] Notice: Database size is 670.36 MB, deleted 63 rows
[2022-08-12 14:50:29.096 5096/T5778] WARN: Could not write() everything in ssend() [/__w/FTL/FTL/src/api/socket.c:245]: Connection reset by peer
[2022-08-12 14:59:00.132 5096/T5100] Notice: Database size is 670.36 MB, deleted 98 rows
[2022-08-12 15:10:00.143 5096/T5100] Notice: Database size is 670.36 MB, deleted 57 rows
[2022-08-12 15:20:00.135 5096/T5100] Notice: Database size is 670.36 MB, deleted 90 rows
[2022-08-12 15:30:00.086 5096/T5100] Notice: Database size is 670.36 MB, deleted 480 rows
[2022-08-12 15:35:39.068 5096M] Resizing "FTL-dns-cache" from 8192 to (768 * 16) == 12288 (/dev/shm: 1.3MB used, 484.0MB total, FTL uses 1.3MB)
[2022-08-12 15:40:00.104 5096/T5100] Notice: Database size is 670.36 MB, deleted 200 rows
[2022-08-12 15:50:00.102 5096/T5100] Notice: Database size is 670.36 MB, deleted 69 rows
[2022-08-12 16:00:00.079 5096/T5100] Notice: Database size is 670.36 MB, deleted 106 rows
[2022-08-12 16:03:20.282 5096M] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2022-08-12 16:03:20.282 5096M] ---------------------------->  FTL crashed!  <----------------------------
[2022-08-12 16:03:20.282 5096M] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2022-08-12 16:03:20.283 5096M] Please report a bug at https://github.com/pi-hole/FTL/issues
[2022-08-12 16:03:20.283 5096M] and include in your report already the following details:
[2022-08-12 16:03:20.283 5096M] FTL has been running for 9504 seconds
[2022-08-12 16:03:20.283 5096M] FTL branch: master
[2022-08-12 16:03:20.283 5096M] FTL version: v5.16.1
[2022-08-12 16:03:20.283 5096M] FTL commit: 5ff5bed
[2022-08-12 16:03:20.283 5096M] FTL date: 2022-07-08 08:44:12 +0100
[2022-08-12 16:03:20.283 5096M] FTL user: started as pihole, ended as pihole
[2022-08-12 16:03:20.283 5096M] Compiled for armv7hf (compiled on CI) using arm-linux-gnueabihf-gcc (Debian 6.3.0-18) 6.3.0 20170516
[2022-08-12 16:03:20.284 5096M] Process details: MID: 5096
[2022-08-12 16:03:20.284 5096M]                  PID: 5096
[2022-08-12 16:03:20.284 5096M]                  TID: 5096
[2022-08-12 16:03:20.284 5096M]                  Name: pihole-FTL
[2022-08-12 16:03:20.284 5096M] Received signal: Segmentation fault
[2022-08-12 16:03:20.284 5096M]      at address: 0x6d000000
[2022-08-12 16:03:20.284 5096M]      with code:  SEGV_MAPERR (Address not mapped to object)
[2022-08-12 16:03:20.284 5096M] Backtrace:
[2022-08-12 16:03:20.285 5096M] B[0000]: /usr/bin/pihole-FTL(generate_backtrace+0x29) [0x4e069a]
[2022-08-12 16:03:20.387 5096M] L[0000]: /__w/FTL/FTL/src/signals.c:99
[2022-08-12 16:03:20.393 5096M] B[0001]: /usr/bin/pihole-FTL(+0x40a4e) [0x4e0a4e]
[2022-08-12 16:03:20.455 5096M] L[0001]: /__w/FTL/FTL/src/signals.c:242
[2022-08-12 16:03:20.461 5096M] B[0002]: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0x76d87120]
[2022-08-12 16:03:20.462 5096M] ------ Listing content of directory /dev/shm ------
[2022-08-12 16:03:20.462 5096M] File Mode User:Group      Size  Filename
[2022-08-12 16:03:20.462 5096M] rwxrwxrwx root:root       260  .
[2022-08-12 16:03:20.462 5096M] rwxr-xr-x root:root         4K  ..
[2022-08-12 16:03:20.463 5096M] rw------- pihole:pihole     4K  FTL-per-client-regex
[2022-08-12 16:03:20.463 5096M] rw------- pihole:pihole    12K  FTL-dns-cache
[2022-08-12 16:03:20.463 5096M] rw------- pihole:pihole    12K  FTL-overTime
[2022-08-12 16:03:20.464 5096M] rw------- pihole:pihole   180K  FTL-queries
[2022-08-12 16:03:20.464 5096M] rw------- pihole:pihole   618K  FTL-upstreams
[2022-08-12 16:03:20.464 5096M] rw------- pihole:pihole   332K  FTL-clients
[2022-08-12 16:03:20.465 5096M] rw------- pihole:pihole    20K  FTL-domains
[2022-08-12 16:03:20.465 5096M] rw------- pihole:pihole    82K  FTL-strings
[2022-08-12 16:03:20.466 5096M] rw------- pihole:pihole    12  FTL-settings
[2022-08-12 16:03:20.466 5096M] rw------- pihole:pihole   244  FTL-counters
[2022-08-12 16:03:20.466 5096M] rw------- pihole:pihole    56  FTL-lock
[2022-08-12 16:03:20.466 5096M] ---------------------------------------------------
[2022-08-12 16:03:20.467 5096M] Please also include some lines from above the !!!!!!!!! header.
[2022-08-12 16:03:20.467 5096M] Thank you for helping us to improve our FTL engine!
[2022-08-12 16:03:20.467 5096M] Waiting for threads to join
[2022-08-12 16:03:20.467 5096M] Thread telnet-IPv4 (0) is idle, terminating it.
[2022-08-12 16:03:20.467 5096M] Thread telnet-IPv6 (1) is idle, terminating it.
[2022-08-12 16:03:20.468 5096M] Thread telnet-socket (2) is idle, terminating it.
[2022-08-12 16:03:20.468 5096M] Thread database (3) is idle, terminating it.
[2022-08-12 16:03:20.469 5096M] Thread housekeeper (4) is idle, terminating it.
[2022-08-12 16:03:20.469 5096M] Thread DNS client (5) is idle, terminating it.
[2022-08-12 16:03:20.470 5096M] All threads joined

**Comment by yubiuser** [comment] 2022-08-12 20:39
Do you ran `PADD`?

**Comment by riddlecp** [comment] 2022-08-12 20:51
Yes, updated yesterday afternoon

**Comment by yubiuser** [comment] 2022-08-12 20:54
Very likely a duplicate of https://github.com/pi-hole/FTL/issues/1394

**Comment by DL6ER** [comment] 2022-08-19 20:10
@riddlecp Do you still see the same issues after upgrading to the latest version of FTL?

**Comment by riddlecp** [comment] 2022-08-19 20:17
I disabled PADD and haven't looked again. I'll update this evening and see
if the behavior is the same. Thank you!

**Comment by DL6ER** [comment] 2022-09-04 11:10
@riddlecp Any update for us?

**Comment by riddlecp** [comment] 2022-09-04 14:52
Yes, it's working now without issue!

Thanks for your help

**Closed** 2022-09-04 16:06 UTC
Labels: Duplicate, Waiting for feedback
