### ISSUE TITLE
SQLite3 message: database is locked in "SELECT VALUE FROM ftl WHERE id = 0;"

### ISSUE THREAD

**Issue by welljsjs** [pi-hole/FTL#625] opened 2019-07-30 14:54 UTC
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_2_

---

**[BUG | ISSUE] Expected Behaviour:**
When restarting the DNS service with the following command:

```sh
sudo pihole restartdns
```
the DNS service should properly restart without crashing.

**[BUG | ISSUE] Actual Behaviour:**
When executing the command (see above), FTL reports the following error messages (entries taken from the log file under `/var/log/pihole-FTL.log`:

```log
[2019-07-30 16:30:20.036 1727] SQLite3 message: database is locked in "SELECT VALUE FROM ftl WHERE id = 0;" (5)
[2019-07-30 16:30:20.036 1727] db_query_int(SELECT VALUE FROM ftl WHERE id = 0;) - SQL error prepare (5): database is locked
[2019-07-30 16:30:20.036 1727] Database version is -2
[2019-07-30 16:30:20.036 1727] Database version incorrect, database not available
```

and FTL crashes. This behaviour does only occur after executing the restart command, not at normal startup.

This might be related to the merged PR #185 

**[BUG | ISSUE] Steps to reproduce:**

- execute `sudo pihole restartdns`

**Log file output [if available]**

see above

**Device specifics**

Hardware Type: rPi, VPS, etc
OS:
```
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10

Linux hostname 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l GNU/Linux

Pi-hole version v4.3.1
AdminLTE version is v4.3
FTL version is v4.3.1
```

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment] 2019-08-01 21:26
Are you able to reproduce this on a fresh install (that is the purpose of "Steps to reproduce")?

Make sure the `pihole` user can write to the `/etc/pihole` folder and `/etc/pihole/pihole-FTL.db`. Run `pihole -d` for a debug token.

**Comment by welljsjs** [comment] 2019-08-02 09:47
> Are you able to reproduce this on a fresh install (that is the purpose of "Steps to reproduce")?

Yes, I am. 

> Make sure the pihole user can write to the /etc/pihole folder and /etc/pihole/pihole-FTL.db. 

Affirmative.

> Run pihole -d for a debug token.

Unable. Well, after executing `sudo pihole restartdns`, the FTL service doesn't run so my Pi is not able to resolve any hostnames which results in the Pi not being able to upload the debug log to the servers (so I cannot provide you the debug token).

**Comment by Mcat12** [comment] 2019-08-02 18:58
I was unable to reproduce this on a fresh install of Debian Buster. Make sure to detail any other steps you may have done after a fresh install, other than calling `pihole restartdns`, or any other relevant environment details.

`pihole -d` will make a debug log at `/var/log/pihole_debug.log`. Upload it to a pastebin site and share the link.

**Comment by DL6ER** [comment] 2019-08-04 16:30
@welljsjs 
> and FTL crashes. 

Can you quote the crash log? The log excerpt you posted does not include any information *where* the crash happened. FTL should surely not crash when the database is not available (for whatever reason!). It would be very nice if you could post some more information but I will also look independently for a probably missing `if` clause or `return` statement.

**Comment by welljsjs** [comment] 2019-08-04 20:03
This is the whole FTL log file: 

```log
[2019-08-04 22:00:33.278 1558] Using log file /var/log/pihole-FTL.log
[2019-08-04 22:00:33.278 1558] ########## FTL started! ##########
[2019-08-04 22:00:33.279 1558] FTL branch: master
[2019-08-04 22:00:33.279 1558] FTL version: v4.3.1
[2019-08-04 22:00:33.279 1558] FTL commit: b60d63f
[2019-08-04 22:00:33.279 1558] FTL date: 2019-05-25 21:37:26 +0200
[2019-08-04 22:00:33.279 1558] FTL user: pihole
[2019-08-04 22:00:33.279 1558] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
[2019-08-04 22:00:33.279 1558]    SOCKET_LISTENING: only local
[2019-08-04 22:00:33.279 1558]    AAAA_QUERY_ANALYSIS: Show AAAA queries
[2019-08-04 22:00:33.279 1558]    MAXDBDAYS: max age for stored queries is 365 days
[2019-08-04 22:00:33.279 1558]    RESOLVE_IPV6: Resolve IPv6 addresses
[2019-08-04 22:00:33.279 1558]    RESOLVE_IPV4: Resolve IPv4 addresses
[2019-08-04 22:00:33.279 1558]    DBINTERVAL: saving to DB file every minute
[2019-08-04 22:00:33.279 1558]    DBFILE: Using /etc/pihole/pihole-FTL.db
[2019-08-04 22:00:33.279 1558]    MAXLOGAGE: Importing up to 24.0 hours of log data
[2019-08-04 22:00:33.279 1558]    PRIVACYLEVEL: Set to 0
[2019-08-04 22:00:33.279 1558]    IGNORE_LOCALHOST: Show queries from localhost
[2019-08-04 22:00:33.280 1558]    BLOCKINGMODE: Pi-hole's IPs for blocked domains
[2019-08-04 22:00:33.280 1558]    ANALYZE_ONLY_A_AND_AAAA: Disabled. Analyzing all queries
[2019-08-04 22:00:33.280 1558]    DBIMPORT: Importing history from database
[2019-08-04 22:00:33.280 1558]    PIDFILE: Using /var/run/pihole-FTL.pid
[2019-08-04 22:00:33.280 1558]    PORTFILE: Using /var/run/pihole-FTL.port
[2019-08-04 22:00:33.280 1558]    SOCKETFILE: Using /var/run/pihole/FTL.sock
[2019-08-04 22:00:33.280 1558]    WHITELISTFILE: Using /etc/pihole/whitelist.txt
[2019-08-04 22:00:33.280 1558]    BLACKLISTFILE: Using /etc/pihole/black.list
[2019-08-04 22:00:33.280 1558]    GRAVITYFILE: Using /etc/pihole/gravity.list
[2019-08-04 22:00:33.280 1558]    REGEXLISTFILE: Using /etc/pihole/regex.list
[2019-08-04 22:00:33.280 1558]    SETUPVARSFILE: Using /etc/pihole/setupVars.conf
[2019-08-04 22:00:33.280 1558]    AUDITLISTFILE: Using /etc/pihole/auditlog.list
[2019-08-04 22:00:33.280 1558]    MACVENDORDB: Using /etc/pihole/macvendor.db
[2019-08-04 22:00:33.280 1558]    PARSE_ARP_CACHE: Active
[2019-08-04 22:00:33.280 1558] Finished config file parsing
[2019-08-04 22:00:33.281 1558] SQLite3 message: database is locked in "SELECT VALUE FROM ftl WHERE id = 0;" (5)
[2019-08-04 22:00:33.282 1558] db_query_int(SELECT VALUE FROM ftl WHERE id = 0;) - SQL error prepare (5): database is locked
[2019-08-04 22:00:33.282 1558] Database version is -2
[2019-08-04 22:00:33.282 1558] Database version incorrect, database not available
[2019-08-04 22:00:33.282 1558]  -> Total DNS queries: 0
[2019-08-04 22:00:33.282 1558]  -> Cached DNS queries: 0
[2019-08-04 22:00:33.282 1558]  -> Forwarded DNS queries: 0
[2019-08-04 22:00:33.282 1558]  -> Exactly blocked DNS queries: 0
[2019-08-04 22:00:33.282 1558]  -> Unknown DNS queries: 0
[2019-08-04 22:00:33.282 1558]  -> Unique domains: 0
[2019-08-04 22:00:33.282 1558]  -> Unique clients: 0
[2019-08-04 22:00:33.282 1558]  -> Known forward destinations: 0
[2019-08-04 22:00:33.282 1558] Successfully accessed setupVars.conf
[2019-08-04 22:00:35.153 1251] Finished final database update
[2019-08-04 22:00:35.154 1251] ########## FTL terminated after 25548.8 ms! ##########
```

**Comment by DL6ER** [comment] 2019-08-04 20:09
Thanks. This does not look like a crash, rather like an ordinary shutdown. The database errors you see might be completely unrelated.

**Comment by welljsjs** [comment] 2019-08-04 20:10
That's weird, because this always happens (as mentioned) when I execute `sudo pihole restartdns`.

**Comment by DL6ER** [comment] 2019-08-05 17:39
Thanks, I checked your pastebin debug log and have two comments:

1. I see you added some custom lines like `server=/fritz.box/192.168.178.1` to your `/etc/dnsmasq.d/01-pihole.conf`. Please modify this file as it gets overwritten during Pi-hole updates. You should rather put such lines into a custom file, like `/etc/dnsmasq.d/99-fritzbox.conf`
2. Looking at your `pihole-FTL.log` it looks pretty much like your FTL starts up just fine and gets immediately terminated afterwards (it shuts down ordinary within about two seconds after startup).
   Questions:
   - Does `sudo service pihole-FTL restart` show the same behavior?
   - What is the output of `sudo journalctl -xe` immediately after a restart failed?

**Comment by welljsjs** [comment] 2019-08-05 17:41
> I see you added some custom lines like ... server=/fritz.box/192.168.178.1 to your /etc/dnsmasq.d/01-pihole.conf

Nope, sorry, I did not modify that file. That's likely the new Pihole feature for conditional forwarding.

**Comment by Mcat12** [comment] 2019-08-05 22:43
What's the output of these commands?
```
ls -l /etc/pihole/pihole-FTL.db
sqlite3 /etc/pihole/pihole-FTL.db "SELECT * FROM ftl"
```

**Comment by welljsjs** [comment] 2019-08-06 09:57
```log
-rw-r--r-- 1 pihole pihole 19865600 Aug  6 11:55 /etc/pihole/pihole-FTL.db

0|3
1|1565085422
2|1563309230
```

**Comment by Mcat12** [comment] 2019-08-07 18:38
`pihole restartdns` simply calls `service pihole-FTL restart`. Do you still see a difference when you call those two?

**Comment by DL6ER** [comment] 2019-08-14 18:26
The restarting issue has to be tracked on the core repo. As we already have a similar issue ticket there, I will close this one.

See https://github.com/pi-hole/pi-hole/issues/2869

**Closed by DL6ER** 2019-08-14 18:26 UTC
Labels: Bug
