### ISSUE TITLE
cache-size cant be set to 0

### ISSUE THREAD

**Issue by wuast94** [pi-hole/FTL#692] opened 2020-02-11 18:12 UTC
Relating to this post its not possible to set cache-size=0 resulting in crashing the FTL
https://discourse.pi-hole.net/t/setting-chache-to-0-crashes-dns/28125

From Doku( https://docs.pi-hole.net/ftldns/dns-cache/): Setting the cache size to zero disables caching

**Comment by wuast94** [comment] 2020-02-11 19:44
not for me .. in the link from pi-hole forum someone else get this strange behavior too. 

when i can provide you more information just ask :) 

 and in pihole web interface it lookes like this: DNS service not running and FTL offline
![image](https://user-images.githubusercontent.com/16965460/74272690-5ab6d080-4d0f-11ea-994c-98c99fe9ba2d.png)

**Comment by DL6ER** [comment] 2020-02-11 20:18
Okay, the other reporter is mentioning a different issue that existed with the Pi-hole v5.0beta code today but got fixed meanwhile. Shall we close this when the issue is resolved for you?

**Comment by wuast94** [comment] 2020-02-11 20:34
for me it isnt resolved :/ 

and by the way i run the actual pihole version not any beta and updated too but that didnt fixed the error

**Comment by wuast94** [comment] 2020-02-14 18:29
is there any thing i can share to help you to find the problem ?

**Comment by DL6ER** [comment] 2020-02-14 19:24
I misread your statement as you wrote with 

> not for me .. in the link from pi-hole forum someone else get this strange behavior too.

so I assumed you meant "the crash does not happen for me but only the other user".

> is there any thing i can share to help you to find the problem ?

Hmm, the embedded `dnsmasq` resolvers seems to hang during starting up and is not doing anything. Please share the content of your `/etc/dnsmasq.conf` as well as the content of all files within `/etc/dnsmasq.d/`.

**Comment by wuast94** [comment] 2020-02-14 19:57
/etc/dnsmasq.conf:
`conf-dir=/etc/dnsmasq.d`
/etc/dnsmasq.d only one file: 01-pihole.conf
```
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Dnsmasq config for Pi-hole's FTLDNS
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

###############################################################################
#      FILE AUTOMATICALLY POPULATED BY PI-HOLE INSTALL/UPDATE PROCEDURE.      #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#        IF YOU WISH TO CHANGE THE UPSTREAM SERVERS, CHANGE THEM IN:          #
#                      /etc/pihole/setupVars.conf                             #
#                                                                             #
#        ANY OTHER CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE           #
#                    WITHIN /etc/dnsmasq.d/yourname.conf                      #
###############################################################################

addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/black.list
addn-hosts=/etc/pihole/local.list


localise-queries


no-resolv



cache-size=10000

log-queries
log-facility=/var/log/pihole.log

local-ttl=2

log-async
server=127.0.0.1#5353
server=::1#5353
domain-needed
bogus-priv
dnssec
trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
trust-anchor=.,20326,8,2,E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D

interface=eth0
```
I now have it at cache size 10000 becouse at 0 the dns server dont work :D but i want it to be 0 to disable the pihole caching

**Comment by DL6ER** [comment] 2020-02-15 07:49
Ah, this makes more sense now. You're using DNSSEC:

> dnssec

The [`dnsmasq` man page](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) sates:
> Because the DNSSEC validation process uses the cache, it is not permitted to reduce the cache size below the default when DNSSEC is enabled.

There should be a message in `/var/log/pihole.log`. Not sure why we haven't checked this until now.

**Comment by wuast94** [comment] 2020-02-15 07:58
Ahh ok now we on the right way :) 

Now the big question ist if there is a way to change this in future releases? I would like to keep dnssec but disable cache.

**Comment by DL6ER** [comment] 2020-02-15 08:03
This is a question that needs to be asked upstream to dnsmasq-discuss@lists.thekelleys.org.uk

We're not making such modifications to the `dnsmasq` code ourselves. To ensure compatibility, such requests have to be made in the `dnsmasq` project itself from where we'll happily import this change when it is done.

**Closed** 2020-02-15 08:03 UTC
Labels: Discussion

**Comment by wuast94** [comment] 2020-02-17 20:27
> This is a question that needs to be asked upstream to [dnsmasq-discuss@lists.thekelleys.org.uk](mailto:dnsmasq-discuss@lists.thekelleys.org.uk)
> 
> We're not making such modifications to the `dnsmasq` code ourselves. To ensure compatibility, such requests have to be made in the `dnsmasq` project itself from where we'll happily import this change when it is done.

after i register an email i wrote them. the conversion was .. bad ? a little bit aggressiv ? read yourself: 
![image](https://user-images.githubusercontent.com/16965460/74684238-ad8aff00-51cb-11ea-8ea3-2c7eb425b634.png)

i think thats not the way to talk each other but hoping that dnsmasq is fixing this is hopeless i think. 

BUT i found a "workaround": 

Disable dnssec in pihole and set cahe to 0 -> restart pihole. 

unbound is using dnssec and pihole dont cache anymore. i testet on many sites if my browser is using dnssec and all test passes fine. 

@DL6ER should this be added in PiHole Doku ? its not that many people who wants to do this and want the finer/better statistics from unbound for grafana dashboards (or similiar) but its helpful

**Comment by DL6ER** [comment] 2020-02-17 20:32
> but hoping that dnsmasq is fixing this is hopeless i think.

Don't extrapolate the opinion of one list member (he is not a developer of the project!) to the entire project.

> should this be added in PiHole Doku ?

I don't think so. It is expected that `unbound` does everything for you as  it is a *validating* recursive DNS server. The validation part is DNSSEC here. Disabling DNSSEC in Pi-hole will cause details being lost on the way down to the client so this is really only a workaround and not a proper solution.

**Comment by wuast94** [comment] 2020-02-17 20:37
and it isnt a real workaround. when i use online tests it seems to be fine but when i use 

` dig pir.org +dnssec +multi`

i dont see the AD part..
