### ISSUE TITLE
Sudden pihole crash

### ISSUE THREAD

**Issue by gurparit** [pi-hole/FTL#448] opened 2018-12-23 19:39 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate 

**Log file output [if available]**

`output`

[2018-12-23 19:13:44.236] FTL has been running for 148256 seconds
[2018-12-23 19:13:44.236] FTL branch: master
[2018-12-23 19:13:44.236] FTL version: v4.1.1
[2018-12-23 19:13:44.236] FTL commit: f5f331b
[2018-12-23 19:13:44.236] FTL date: 2018-12-21 10:32:10 -0600
[2018-12-23 19:13:44.237] FTL user: pihole
[2018-12-23 19:13:44.237] Received signal: Segmentation fault
[2018-12-23 19:13:44.237]      at address: 0
[2018-12-23 19:13:44.237]      with code: SEGV_MAPERR (Address not mapped to object)
[2018-12-23 19:13:44.238] Backtrace:
[2018-12-23 19:13:44.238] B[0000]: /usr/bin/pihole-FTL(+0x1a09a) [0x49909a]
[2018-12-23 19:13:44.238] B[0001]: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0 [0x76de76c0]
[2018-12-23 19:13:44.238] Thank you for helping us to improve our FTL engine!
[2018-12-23 19:13:44.239] FTL terminated!
[2018-12-23 19:29:21.006] Using log file /var/log/pihole-FTL.log

--

**Device specifics**

Hardware Type: rPi, VPS, etc
OS: rPi 2

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment] 2018-12-23 19:42
Duplicate of #444.
Update to the latest version, v4.1.2.

**Closed by Mcat12** 2018-12-23 19:42 UTC
