### ISSUE TITLE
FTL Crash

### ISSUE THREAD

**Issue by tomino1983** [pi-hole/FTL#1483] opened 2022-11-16 17:15 UTC
eT093WRO[2022-11-16 15:19:00.140 22069/T22080] Notice: Database size is 929.64 MB, deleted 50 rows
[2022-11-16 15:30:00.138 22069/T22080] Notice: Database size is 929.64 MB, deleted 192 rows
[2022-11-16 15:40:00.129 22069/T22080] Notice: Database size is 929.64 MB, deleted 146 rows
[2022-11-16 15:50:00.136 22069/T22080] Notice: Database size is 929.64 MB, deleted 200 rows
[2022-11-16 16:00:00.075 22069/T22080] Notice: Database size is 929.64 MB, deleted 409 rows
[2022-11-16 16:10:00.138 22069/T22080] Notice: Database size is 929.64 MB, deleted 99 rows
[2022-11-16 16:20:00.052 22069/T22080] Notice: Database size is 929.64 MB, deleted 138 rows
[2022-11-16 16:30:00.189 22069/T22080] Notice: Database size is 929.64 MB, deleted 139 rows
[2022-11-16 16:40:00.126 22069/T22080] Notice: Database size is 929.64 MB, deleted 133 rows
[2022-11-16 16:50:00.077 22069/T22080] Notice: Database size is 929.64 MB, deleted 110 rows
[2022-11-16 17:00:00.144 22069/T22080] Notice: Database size is 929.64 MB, deleted 100 rows
[2022-11-16 17:10:00.101 22069/T22080] Notice: Database size is 929.64 MB, deleted 100 rows
[2022-11-16 17:20:00.069 22069/T22080] Notice: Database size is 929.64 MB, deleted 133 rows
[2022-11-16 17:30:00.136 22069/T22080] Notice: Database size is 929.64 MB, deleted 40 rows
[2022-11-16 17:40:00.165 22069/T22080] Notice: Database size is 929.64 MB, deleted 115 rows
[2022-11-16 17:50:00.170 22069/T22080] Notice: Database size is 929.64 MB, deleted 106 rows
[2022-11-16 17:57:08.656 30166/F22069] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2022-11-16 17:57:08.656 30166/F22069] ---------------------------->  FTL crashed!  <----------------------------
[2022-11-16 17:57:08.656 30166/F22069] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2022-11-16 17:57:08.656 30166/F22069] Please report a bug at https://github.com/pi-hole/FTL/issues
[2022-11-16 17:57:08.656 30166/F22069] and include in your report already the following details:
[2022-11-16 17:57:08.656 30166/F22069] FTL has been running for 68891 seconds
[2022-11-16 17:57:08.656 30166/F22069] FTL branch: master
[2022-11-16 17:57:08.656 30166/F22069] FTL version: v5.19.1
[2022-11-16 17:57:08.657 30166/F22069] FTL commit: b48b3e1f
[2022-11-16 17:57:08.657 30166/F22069] FTL date: 2022-11-14 22:01:50 +0000
[2022-11-16 17:57:08.657 30166/F22069] FTL user: started as pihole, ended as pihole
[2022-11-16 17:57:08.657 30166/F22069] Compiled for armv7hf (compiled on CI) using arm-linux-gnueabihf-gcc (Debian 8.3.0-2) 8.3.0
[2022-11-16 17:57:08.657 30166/F22069] Process details: MID: 22069
[2022-11-16 17:57:08.657 30166/F22069]                  PID: 30166
[2022-11-16 17:57:08.657 30166/F22069]                  TID: 30166
[2022-11-16 17:57:08.657 30166/F22069]                  Name: pihole-FTL
[2022-11-16 17:57:08.657 30166/F22069] Received signal: Segmentation fault
[2022-11-16 17:57:08.657 30166/F22069]      at address: 0xb6f51008
[2022-11-16 17:57:08.658 30166/F22069]      with code:  SEGV_MAPERR (Address not mapped to object)
[2022-11-16 17:57:08.658 30166/F22069] Backtrace:
[2022-11-16 17:57:08.660 30166/F22069] B[0000]: /usr/bin/pihole-FTL(generate_backtrace+0x2d) [0x4db46e]
[2022-11-16 17:57:08.754 30166/F22069] L[0000]: /__w/FTL/FTL/src/signals.c:99
[2022-11-16 17:57:08.756 30166/F22069] B[0001]: /usr/bin/pihole-FTL(+0x3b7fe) [0x4db7fe]
[2022-11-16 17:57:08.808 30166/F22069] L[0001]: /__w/FTL/FTL/src/signals.c:242
[2022-11-16 17:57:08.810 30166/F22069] B[0002]: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb6d3b120]
[2022-11-16 17:57:08.810 30166/F22069] B[0003]: /usr/bin/pihole-FTL(_lock_shm+0x55) [0x4da906]
[2022-11-16 17:57:08.863 30166/F22069] L[0003]: /__w/FTL/FTL/src/shmem.c:420 (discriminator 1)
[2022-11-16 17:57:08.865 30166/F22069] B[0004]: /usr/bin/pihole-FTL(_FTL_new_query+0x1ed) [0x4d034e]
[2022-11-16 17:57:08.920 30166/F22069] L[0004]: /__w/FTL/FTL/src/dnsmasq_interface.c:628
[2022-11-16 17:57:08.923 30166/F22069] B[0005]: /usr/bin/pihole-FTL(tcp_request+0x62b) [0x500770]
[2022-11-16 17:57:08.980 30166/F22069] L[0005]: /__w/FTL/FTL/src/dnsmasq/forward.c:2319 (discriminator 4)
[2022-11-16 17:57:08.983 30166/F22069] B[0006]: /usr/bin/pihole-FTL(+0x57072) [0x4f7072]
[2022-11-16 17:57:09.039 30166/F22069] L[0006]: /__w/FTL/FTL/src/dnsmasq/dnsmasq.c:2053
[2022-11-16 17:57:09.041 30166/F22069] B[0007]: /usr/bin/pihole-FTL(main_dnsmasq+0xe5b) [0x4f86fc]
[2022-11-16 17:57:09.097 30166/F22069] L[0007]: /__w/FTL/FTL/src/dnsmasq/dnsmasq.c:1278
[2022-11-16 17:57:09.100 30166/F22069] B[0008]: /usr/bin/pihole-FTL(main+0xbd) [0x4c6a8e]
[2022-11-16 17:57:09.151 30166/F22069] L[0008]: /__w/FTL/FTL/src/main.c:118
[2022-11-16 17:57:09.154 30166/F22069] B[0009]: /lib/arm-linux-gnueabihf/libc.so.6(__libc_start_main+0x10c) [0xb6d25718]
[2022-11-16 17:57:09.154 30166/F22069] ------ Listing content of directory /dev/shm ------
[2022-11-16 17:57:09.154 30166/F22069] File Mode User:Group      Size  Filename
[2022-11-16 17:57:09.154 30166/F22069] rwxrwxrwx root:root       320  .
[2022-11-16 17:57:09.154 30166/F22069] rwxr-xr-x root:root         4K  ..
[2022-11-16 17:57:09.154 30166/F22069] rw------- pihole:pihole     4K  FTL-per-client-regex
[2022-11-16 17:57:09.154 30166/F22069] rw------- pihole:pihole     4K  FTL-dns-cache
[2022-11-16 17:57:09.154 30166/F22069] rw------- pihole:pihole    12K  FTL-overTime
[2022-11-16 17:57:09.155 30166/F22069] rw------- pihole:pihole     3M  FTL-queries
[2022-11-16 17:57:09.155 30166/F22069] rw------- pihole:pihole   618K  FTL-upstreams
[2022-11-16 17:57:09.155 30166/F22069] rw------- pihole:pihole   332K  FTL-clients
[2022-11-16 17:57:09.155 30166/F22069] rw------- pihole:pihole   143K  FTL-domains
[2022-11-16 17:57:09.155 30166/F22069] rw------- pihole:pihole   246K  FTL-strings
[2022-11-16 17:57:09.155 30166/F22069] rw------- pihole:pihole    16  FTL-settings
[2022-11-16 17:57:09.155 30166/F22069] rw------- pihole:pihole   248  FTL-counters
[2022-11-16 17:57:09.155 30166/F22069] rw------- pihole:pihole    56  FTL-lock
[2022-11-16 17:57:09.156 30166/F22069] rw-r--r-- pi:pi           264  runcommand.log
[2022-11-16 17:57:09.156 30166/F22069] rw-r--r-- pi:pi           168  retroarch.cfg
[2022-11-16 17:57:09.156 30166/F22069] rw-r--r-- pi:pi           260  runcommand.info
[2022-11-16 17:57:09.156 30166/F22069] ---------------------------------------------------
[2022-11-16 17:57:09.156 30166/F22069] Please also include some lines from above the !!!!!!!!! header.
[2022-11-16 17:57:09.156 30166/F22069] Thank you for helping us to improve our FTL engine!
[2022-11-16 17:57:09.156 30166/F22069] Asking parent pihole-FTL (PID 22069) to shut down
[2022-11-16 17:57:09.156 30166/F22069] FTL fork terminated!
[2022-11-16 17:57:09.156 22069M] Received: Real-time signal 2 (36 -> 2)
[2022-11-16 17:57:09.156 22069M] Shutting down...
[2022-11-16 17:57:09.157 30166/F22069] Failed to unlock inner SHM lock: Operation not permitted
[2022-11-16 17:57:09.408 22069M] Finished final database update (stored 0 queries)
[2022-11-16 17:57:09.408 22069M] Waiting for threads to join
[2022-11-16 17:57:09.408 22069M] Thread database (0) is idle, terminating it.
[2022-11-16 17:57:09.409 22069M] Thread housekeeper (1) is idle, terminating it.
[2022-11-16 17:57:09.409 22069M] Thread DNS client (2) is idle, terminating it.
[2022-11-16 17:57:09.410 22069M] All threads joined
[2022-11-16 17:57:09.410 22069M] Joining API worker thread 0
[2022-11-16 17:57:09.410 22069M] Joining API worker thread 1
[2022-11-16 17:57:09.410 22069M] Joining API worker thread 2
[2022-11-16 17:57:09.410 22069M] Joining API worker thread 3
[2022-11-16 17:57:09.410 22069M] Joining API worker thread 4
[2022-11-16 17:57:09.413 22069M] ########## FTL terminated after 19h 8m 11s  (code 1)! ##########
[2022-11-16 17:59:13.426 30321M] Using log file /var/log/pihole/FTL.log

**Comment by tomino1983** [comment] 2022-11-16 17:20
It look like related to the DB size but id doesn't make sense. I have 22 GB free on the SDCARD on my RPI4.

**Comment by rdwebdesign** [comment] 2022-11-16 18:03
Possible duplicate of https://github.com/pi-hole/FTL/issues/1478

**Closed** 2022-11-16 18:15 UTC
