### ISSUE TITLE
FTL Crash

### ISSUE THREAD

**Issue by doadin** [pi-hole/FTL#2119] opened 2024-11-17 03:12 UTC
### Versions
Core
    Version is v5.18.3-550-g112b9617 (Latest: null)
    Branch is development
    Hash is 112b9617 (Latest: d2cbe1f7)
Web
    Version is v5.21-1012-gc689fdc7 (Latest: null)
    Branch is development
    Hash is c689fdc7 (Latest: c689fdc7)
FTL
    Version is vDev-988a3c3 (Latest: null)
    Branch is development
    Hash is 988a3c3d (Latest: 988a3c3d)

### Platform
- Raspberry Pi Raspbian 12

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

2024-11-16 20:01:09.809 INFO Received 8/8 valid NTP replies from north-america.pool.ntp.org
2024-11-16 20:01:09.809 INFO Time offset: -1.266745e+01 ms (excluded 0 outliers)
2024-11-16 20:01:09.809 INFO Round-trip delay: 4.357225e+01 ms (excluded 0 outliers)
2024-11-16 21:04:44.799 INFO Received 8/8 valid NTP replies from north-america.pool.ntp.org
2024-11-16 21:04:44.800 INFO Time offset: -2.693415e+00 ms (excluded 1 outliers)
2024-11-16 21:04:44.800 INFO Round-trip delay: 3.958695e+01 ms (excluded 1 outliers)
2024-11-16 21:29:41.733 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:29:43.261 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:29:43.323 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:31:44.024 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:31:44.253 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:31:44.618 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:31:46.196 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:31:46.426 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:31:46.458 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:31:46.495 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:31:47.572 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:31:47.615 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:31:47.630 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:31:53.497 WARNING Connection error (127.0.0.1#5335): failed to send TCP(read_write) packet (Connection prematurely closed by remote server)
2024-11-16 21:32:00.128 INFO !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2024-11-16 21:32:00.128 INFO ---------------------------->  FTL crashed!  <----------------------------
2024-11-16 21:32:00.129 INFO !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2024-11-16 21:32:00.129 INFO Please report a bug at https://github.com/pi-hole/FTL/issues
2024-11-16 21:32:00.129 INFO and include in your report already the following details:
2024-11-16 21:32:00.129 INFO FTL has been running for 57675 seconds
2024-11-16 21:32:00.129 INFO FTL branch: development
2024-11-16 21:32:00.129 INFO FTL version: vDev-988a3c3
2024-11-16 21:32:00.129 INFO FTL commit: 988a3c3d
2024-11-16 21:32:00.129 INFO FTL date: 2024-11-14 18:44:44 +0100
2024-11-16 21:32:00.129 INFO FTL user: started as pihole, ended as pihole
2024-11-16 21:32:00.130 INFO Compiled for linux/arm64/v8 (compiled on CI) using cc (Alpine 13.2.1_git20240309) 13.2.1 20240309
2024-11-16 21:32:00.130 INFO Process details: MID: 24933
2024-11-16 21:32:00.130 INFO                  PID: 24933
2024-11-16 21:32:00.130 INFO                  TID: 24935
2024-11-16 21:32:00.130 INFO                  Name: database
2024-11-16 21:32:00.130 INFO Received signal: Segmentation fault
2024-11-16 21:32:00.130 INFO      at address: 0
2024-11-16 21:32:00.130 INFO      with code:  SEGV_MAPERR (Address not mapped to object)
2024-11-16 21:32:00.130 INFO !!! INFO: pihole-FTL has not been compiled with glibc/backtrace support, not generating one !!!
2024-11-16 21:32:00.131 INFO ------ Listing content of directory /dev/shm ------
2024-11-16 21:32:00.131 INFO File Mode User:Group      Size  Filename
2024-11-16 21:32:00.131 INFO rwxrwxrwx root:root       360   .
2024-11-16 21:32:00.131 INFO rwxr-xr-x root:root         4K  ..
2024-11-16 21:32:00.131 INFO rw------- pihole:pihole    88   FTL-lock
2024-11-16 21:32:00.132 INFO rw------- pihole:pihole   328   FTL-counters
2024-11-16 21:32:00.132 INFO rw------- pihole:pihole   136   FTL-settings
2024-11-16 21:32:00.132 INFO rw------- pihole:pihole   205K  FTL-strings
2024-11-16 21:32:00.133 INFO rw------- pihole:pihole   143K  FTL-domains
2024-11-16 21:32:00.133 INFO rw------- pihole:pihole   348K  FTL-clients
2024-11-16 21:32:00.134 INFO rw------- pihole:pihole    29K  FTL-upstreams
2024-11-16 21:32:00.134 INFO rw------- pihole:pihole     6M  FTL-queries
2024-11-16 21:32:00.134 INFO rw------- pihole:pihole     8K  FTL-overTime
2024-11-16 21:32:00.135 INFO rw------- pihole:pihole   348K  FTL-dns-cache
2024-11-16 21:32:00.135 INFO rw------- pihole:pihole     4K  FTL-per-client-regex
2024-11-16 21:32:00.135 INFO rw------- pihole:pihole   569K  FTL-fifo-log
2024-11-16 21:32:00.136 INFO rw------- pihole:pihole     4K  FTL-clients-lookup
2024-11-16 21:32:00.136 INFO rw------- pihole:pihole    37K  FTL-domains-lookup
2024-11-16 21:32:00.136 INFO rw------- pihole:pihole    61K  FTL-dns-cache-lookup
2024-11-16 21:32:00.137 INFO rw------- pihole:pihole   786K  FTL-recycler
2024-11-16 21:32:00.137 INFO ---------------------------------------------------
2024-11-16 21:32:00.137 INFO Please also include some lines from above the !!!!!!!!! header.
2024-11-16 21:32:00.137 INFO Thank you for helping us to improve our FTL engine!
2024-11-16 21:32:00.137 INFO Waiting for threads to join
2024-11-16 21:32:00.151 INFO Terminating timer thread
2024-11-16 21:32:00.152 INFO Terminating GC thread
2024-11-16 21:32:01.086 INFO Terminating resolver thread
2024-11-16 21:32:02.137 INFO Thread database (0) is still busy, cancelling it.
2024-11-16 21:48:38.624 ERROR Error when obtaining outer SHM lock: Previous owner died
2024-11-16 21:48:38.624 ERROR Error when obtaining inner SHM lock: Previous owner died

## Debug Token

- URL:  Your debug token is: https://tricorder.pi-hole.net/hiwj5ArN/

**Comment by DL6ER** [comment] 2024-11-17 08:28
Probably a duplicate of #2112 which is currently under active discussion

**Comment by DL6ER** [comment] 2024-11-19 17:08
@doadin Please try again on the latest `development` version of FTL.

**Closed** 2024-11-29 20:12 UTC
Labels: Duplicate, Pi-hole v6.0
