### ISSUE TITLE
FTL Crashing randomly

### ISSUE THREAD

**Issue by joekellyco** [pi-hole/FTL#1488] opened 2022-11-17 17:47 UTC
Since the last 2 updates for PiHole I've had FTL crash on my Raspberry Pi 4B 2GB.   I've not had any issues with PiHole for a year and this is the first time I've seen FTL just randomly take itself out.  

last one I captured the crash in the logs:
[2022-11-16 12:00:00.114 338750/F313999] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2022-11-16 12:00:00.115 338750/F313999] ---------------------------->  FTL crashed!  <----------------------------
[2022-11-16 12:00:00.115 338750/F313999] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2022-11-16 12:00:00.115 338750/F313999] Please report a bug at https://github.com/pi-hole/FTL/issues
[2022-11-16 12:00:00.115 338750/F313999] and include in your report already the following details:
[2022-11-16 12:00:00.115 338750/F313999] FTL has been running for 92535 seconds
[2022-11-16 12:00:00.115 338750/F313999] FTL branch: master
[2022-11-16 12:00:00.115 338750/F313999] FTL version: v5.19.1
[2022-11-16 12:00:00.115 338750/F313999] FTL commit: b48b3e1f
[2022-11-16 12:00:00.115 338750/F313999] FTL date: 2022-11-14 22:01:50 +0000
[2022-11-16 12:00:00.116 338750/F313999] FTL user: started as pihole, ended as pihole
[2022-11-16 12:00:00.116 338750/F313999] Compiled for aarch64 (compiled on CI) using aarch64-linux-gnu-gcc (Debian 8.3.0-2)>
[2022-11-16 12:00:00.116 338750/F313999] Process details: MID: 313999
[2022-11-16 12:00:00.116 338750/F313999]                  PID: 338750
[2022-11-16 12:00:00.116 338750/F313999]                  TID: 338750
[2022-11-16 12:00:00.116 338750/F313999]                  Name: pihole-FTL
[2022-11-16 12:00:00.116 338750/F313999] Received signal: Segmentation fault
[2022-11-16 12:00:00.116 338750/F313999]      at address: 0xffff9458e008
[2022-11-16 12:00:00.117 338750/F313999]      with code:  SEGV_MAPERR (Address not mapped to object)
[2022-11-16 12:00:00.124 338750/F313999] Backtrace:
[2022-11-16 12:00:00.125 338750/F313999] B[0000]: /usr/bin/pihole-FTL(generate_backtrace+0x38) [0xaaaac8cab300]
[2022-11-16 12:00:00.392 338750/F313999] L[0000]: /__w/FTL/FTL/src/signals.c:98
[2022-11-16 12:00:00.395 338750/F313999] B[0001]: /usr/bin/pihole-FTL(+0x5b7d4) [0xaaaac8cab7d4]
[2022-11-16 12:00:00.438 338750/F313999] L[0001]: /__w/FTL/FTL/src/signals.c:242
[2022-11-16 12:00:00.441 338750/F313999] B[0002]: linux-vdso.so.1(__kernel_rt_sigreturn+0) [0xffff945ce7dc]
[2022-11-16 12:00:00.441 338750/F313999] B[0003]: /usr/bin/pihole-FTL(_lock_shm+0x88) [0xaaaac8caa338]
[2022-11-16 12:00:00.479 338750/F313999] L[0003]: /__w/FTL/FTL/src/shmem.c:420 (discriminator 1)
[2022-11-16 12:00:00.482 338750/F313999] B[0004]: /usr/bin/pihole-FTL(_FTL_new_query+0x2b8) [0xaaaac8c9cff8]
[2022-11-16 12:00:00.530 338750/F313999] L[0004]: /__w/FTL/FTL/src/dnsmasq_interface.c:628
[2022-11-16 12:00:00.533 338750/F313999] B[0005]: /usr/bin/pihole-FTL(tcp_request+0x6a4) [0xaaaac8cdca4c]
[2022-11-16 12:00:00.586 338750/F313999] L[0005]: /__w/FTL/FTL/src/dnsmasq/forward.c:2314 (discriminator 4)
[2022-11-16 12:00:00.590 338750/F313999] B[0006]: /usr/bin/pihole-FTL(+0x7fa7c) [0xaaaac8ccfa7c]
[2022-11-16 12:00:00.641 338750/F313999] L[0006]: /__w/FTL/FTL/src/dnsmasq/dnsmasq.c:2053
[2022-11-16 12:00:00.645 338750/F313999] B[0007]: /usr/bin/pihole-FTL(main_dnsmasq+0xfc0) [0xaaaac8cd1598]
[2022-11-16 12:00:00.696 338750/F313999] L[0007]: /__w/FTL/FTL/src/dnsmasq/dnsmasq.c:1278
[2022-11-16 12:00:00.700 338750/F313999] B[0008]: /usr/bin/pihole-FTL(main+0x100) [0xaaaac8c914b0]
[2022-11-16 12:00:00.735 338750/F313999] L[0008]: /__w/FTL/FTL/src/main.c:118
[2022-11-16 12:00:00.738 338750/F313999] B[0009]: /lib/aarch64-linux-gnu/libc.so.6(+0x273fc) [0xffff943273fc]
[2022-11-16 12:00:00.738 338750/F313999] B[0010]: /lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0x98) [0xffff943274cc]
[2022-11-16 12:00:00.739 338750/F313999] B[0011]: /usr/bin/pihole-FTL(+0x41978) [0xaaaac8c91978]
[2022-11-16 12:00:00.804 338750/F313999] L[0011]: ??:?
[2022-11-16 12:00:00.812 338750/F313999] ------ Listing content of directory /dev/shm ------
[2022-11-16 12:00:00.812 338750/F313999] File Mode User:Group      Size  Filename
[2022-11-16 12:00:00.812 338750/F313999] rwxrwxrwx root:root       260  .
[2022-11-16 12:00:00.813 338750/F313999] rwxr-xr-x root:root        14K  ..
[2022-11-16 12:00:00.813 338750/F313999] rw------- pihole:pihole     4K  FTL-per-client-regex
[2022-11-16 12:00:00.813 338750/F313999] rw------- pihole:pihole   172K  FTL-dns-cache

**Comment by DL6ER** [comment] 2022-11-17 17:48
Thanks for your report and sorry for the inconvenience. This is already known and fixed. Please update to FTL v5.19.2

**Comment by PromoFaux** [comment] 2022-11-17 17:48
Duplicate of https://github.com/pi-hole/FTL/issues/1478

**Closed by PromoFaux** 2022-11-17 17:48 UTC

**Comment by joekellyco** [comment] 2022-11-17 17:50
Ohh thanks everyone, I didnt see an update available!
