### ISSUE TITLE
FTL crashed

### ISSUE THREAD

**Issue by tempohouse** [pi-hole/FTL#791] opened 2020-05-26 07:44 UTC
Hi all, thanks so much for this project - I've had it running for a little over a year and it's been superb.  I had my first ever issue with it today, when it seems that FTL crashed.  'pihole restartdns' brought everything back to life, but I thought I'd post this info below in case it helps anybody out.  
This is running on Centos 7.7, on an old i5 and 8GBs of RAM.  Happy to provide any more info - please just fire away :)
Cheers, C
-----
[2020-05-26 17:00:47.688 1368] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-05-26 17:00:47.688 1368] ---------------------------->  FTL crashed!  <----------------------------
[2020-05-26 17:00:47.688 1368] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-05-26 17:00:47.688 1368] Please report a bug at https://github.com/pi-hole/FTL/issues
[2020-05-26 17:00:47.688 1368] and include in your report already the following details:
[2020-05-26 17:00:47.688 1368] FTL has been running for 762260 seconds
[2020-05-26 17:00:47.688 1368] FTL branch: master
[2020-05-26 17:00:47.688 1368] FTL version: v5.0
[2020-05-26 17:00:47.688 1368] FTL commit: 3d7c095
[2020-05-26 17:00:47.688 1368] FTL date: 2020-05-10 18:58:38 +0100
[2020-05-26 17:00:47.688 1368] FTL user: started as pihole, ended as pihole
[2020-05-26 17:00:47.688 1368] Compiled for x86_64 (compiled on CI) using gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
[2020-05-26 17:00:47.688 1368] Received signal: Segmentation fault
[2020-05-26 17:00:47.688 1368]      at address: 0x7f74081e47f0
[2020-05-26 17:00:47.688 1368]      with code: SEGV_MAPERR (Address not mapped to object)
[2020-05-26 17:00:47.746 1368] Backtrace:
[2020-05-26 17:00:47.751 1368] B[0000]: 0x55dd1fc556f9, /usr/bin/pihole-FTL(+0x316f9) [0x55dd1fc556f9]
[2020-05-26 17:00:47.751 1368] B[0001]: 0x7f74087e6630, /lib64/libpthread.so.0(+0xf630) [0x7f74087e6630]
[2020-05-26 17:00:47.751 1368] B[0002]: 0x55dd1fc5cf1b, /usr/bin/pihole-FTL(resolveClients+0x15b) [0x55dd1fc5cf1b]
[2020-05-26 17:00:47.751 1368] B[0003]: 0x55dd1fc5d1f7, /usr/bin/pihole-FTL(DNSclient_thread+0xe7) [0x55dd1fc5d1f7]
[2020-05-26 17:00:47.751 1368] B[0004]: 0x7f74087deea5, /lib64/libpthread.so.0(+0x7ea5) [0x7f74087deea5]
[2020-05-26 17:00:47.751 1368] B[0005]: 0x7f74085078dd, /lib64/libc.so.6(clone+0x6d) [0x7f74085078dd]
[2020-05-26 17:00:47.751 1368] ------ Listing content of directory /dev/shm ------
[2020-05-26 17:00:47.751 1368] File Mode User:Group  Filesize Filename
[2020-05-26 17:00:47.751 1368] rwxrwxrwx root:root 300 .
[2020-05-26 17:00:47.751 1368] rwxr-xr-x root:root 3K ..
[2020-05-26 17:00:47.752 1368] rw-r--r-- plex:plex 32 sem.F8EEB26D-AB23-4061-8250-130AB5285A4A
[2020-05-26 17:00:47.752 1368] rw-r--r-- plex:plex 32 sem.9334581e-7251-4ef7-a8ec-5bfe8e89ff68
[2020-05-26 17:00:47.752 1368] rw------- pihole:pihole 4K FTL-per-client-regex
[2020-05-26 17:00:47.752 1368] rw------- pihole:pihole 799K FTL-dns-cache
[2020-05-26 17:00:47.752 1368] rw------- pihole:pihole 12K FTL-overTime
[2020-05-26 17:00:47.752 1368] rw------- pihole:pihole 3M FTL-queries
[2020-05-26 17:00:47.752 1368] rw------- pihole:pihole 4K FTL-upstreams
[2020-05-26 17:00:47.752 1368] rw------- pihole:pihole 225K FTL-clients
[2020-05-26 17:00:47.752 1368] rw------- pihole:pihole 295K FTL-domains
[2020-05-26 17:00:47.752 1368] rw------- pihole:pihole 283K FTL-strings
[2020-05-26 17:00:47.752 1368] rw------- pihole:pihole 12 FTL-settings
[2020-05-26 17:00:47.752 1368] rw------- pihole:pihole 124 FTL-counters
[2020-05-26 17:00:47.752 1368] rw------- pihole:pihole 48 FTL-lock
[2020-05-26 17:00:47.752 1368] ---------------------------------------------------
[2020-05-26 17:00:47.752 1368] Thank you for helping us to improve our FTL engine!
[2020-05-26 17:00:47.752 1368] FTL terminated!

**Comment by DL6ER** [comment] 2020-05-26 22:53
This is a duplicate of the crash reported in  #785 (it is difficult to see this, I agree). We should follow the process in there. If you can attach a debugger as described in #785, that would be awesome!

**Closed by DL6ER** 2020-05-26 22:53 UTC
