### ISSUE TITLE
FTL not found 404

### ISSUE THREAD

**Issue by jxer** [pi-hole/FTL#346] opened 2018-08-08 19:26 UTC
as previously stated ftl does not upgrade due to 404 error

**Comment by DL6ER** [comment] 2018-08-08 19:29
Duplicate of #229 and not actually a problem of the FTL daemon. Please contribute to the issue ticket under https://github.com/pi-hole/pi-hole/issues/2336

**Closed by DL6ER** 2018-08-08 19:29 UTC

**Comment by jxer** [comment] 2018-08-08 19:51
@DL6ER 
i was literally told to open this??????

**Comment by Mcat12** [comment] 2018-08-08 19:54
@PromoFaux asked you to open a new issue in a different repo (pi-hole/pi-hole), not this one (pi-hole/FTL):
https://github.com/pi-hole/FTL/issues/229#issuecomment-411475244

**Comment by Mcat12** [comment] 2018-08-08 19:56
It would also help if you linked what you were referencing with "as previously stated".
