### ISSUE TITLE
FTL Crashed

### ISSUE THREAD

**Issue by moeskerv** [pi-hole/FTL#803] opened 2020-06-05 16:49 UTC
I also see this issue every now and then since I updated to version 5 on my Raspberry PI. 

[2020-06-05 16:00:00.324 1790] Notice: Database size is 1444.54 MB, deleted 3899 rows
[2020-06-05 17:00:00.339 1790] Notice: Database size is 1444.54 MB, deleted 4675 rows
[2020-06-05 17:12:57.443 1790] Resizing "/FTL-strings" from 167936 to 172032
[2020-06-05 17:59:00.272 1790] Notice: Database size is 1444.54 MB, deleted 2990 rows
[2020-06-05 18:01:43.690 1790] Resizing "/FTL-dns-cache" from 126976 to 131072
[2020-06-05 18:18:09.974 1790] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-06-05 18:18:09.975 1790] ---------------------------->  FTL crashed!  <----------------------------
[2020-06-05 18:18:09.975 1790] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-06-05 18:18:09.975 1790] Please report a bug at https://github.com/pi-hole/FTL/issues
[2020-06-05 18:18:09.975 1790] and include in your report already the following details:
[2020-06-05 18:18:09.975 1790] FTL has been running for 128447 seconds
[2020-06-05 18:18:09.975 1790] FTL branch: master
[2020-06-05 18:18:09.975 1790] FTL version: v5.0
[2020-06-05 18:18:09.975 1790] FTL commit: 3d7c095
[2020-06-05 18:18:09.975 1790] FTL date: 2020-05-10 18:58:38 +0100
[2020-06-05 18:18:09.975 1790] FTL user: started as pihole, ended as pihole
[2020-06-05 18:18:09.975 1790] Compiled for armhf (compiled on CI) using arm-linux-gnueabihf-gcc (Debian 6.3.0-18) 6.3.0 20170516
[2020-06-05 18:18:09.975 1790] Received signal: Segmentation fault
[2020-06-05 18:18:09.975 1790]      at address: 0x7a66652d
[2020-06-05 18:18:09.975 1790]      with code: SEGV_MAPERR (Address not mapped to object)
[2020-06-05 18:18:09.975 1790] Backtrace:
[2020-06-05 18:18:09.976 1790] B[0000]: 0x4dd8e4, /usr/bin/pihole-FTL(+0x238e4) [0x4dd8e4]
[2020-06-05 18:18:09.976 1790] B[0001]: 0x76da8130, /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0x76da8130]
[2020-06-05 18:18:09.976 1790] B[0002]: 0x5019da, /usr/bin/pihole-FTL(+0x479da) [0x5019da]
[2020-06-05 18:18:09.976 1790] B[0003]: 0x502fcc, /usr/bin/pihole-FTL(main_dnsmasq+0xc07) [0x502fcc]
[2020-06-05 18:18:09.976 1790] B[0004]: 0x4d3da8, /usr/bin/pihole-FTL(main+0xa7) [0x4d3da8]
[2020-06-05 18:18:09.976 1790] B[0005]: 0x76d92718, /lib/arm-linux-gnueabihf/libc.so.6(__libc_start_main+0x10c) [0x76d92718]
[2020-06-05 18:18:09.976 1790] ------ Listing content of directory /dev/shm ------
[2020-06-05 18:18:09.976 1790] File Mode User:Group  Filesize Filename
[2020-06-05 18:18:09.976 1790] rwxrwxrwx root:root 260 .
[2020-06-05 18:18:09.976 1790] rwxr-xr-x root:root 4K ..
[2020-06-05 18:18:09.976 1790] rw------- pihole:pihole 4K FTL-per-client-regex
[2020-06-05 18:18:09.977 1790] rw------- pihole:pihole 131K FTL-dns-cache
[2020-06-05 18:18:09.977 1790] rw------- pihole:pihole 29K FTL-overTime
[2020-06-05 18:18:09.977 1790] rw------- pihole:pihole 4M FTL-queries
[2020-06-05 18:18:09.977 1790] rw------- pihole:pihole 20K FTL-upstreams
[2020-06-05 18:18:09.977 1790] rw------- pihole:pihole 643K FTL-clients
[2020-06-05 18:18:09.977 1790] rw------- pihole:pihole 131K FTL-domains
[2020-06-05 18:18:09.978 1790] rw------- pihole:pihole 172K FTL-strings
[2020-06-05 18:18:09.978 1790] rw------- pihole:pihole 12 FTL-settings
[2020-06-05 18:18:09.978 1790] rw------- pihole:pihole 124 FTL-counters
[2020-06-05 18:18:09.978 1790] rw------- pihole:pihole 28 FTL-lock
[2020-06-05 18:18:09.978 1790] ---------------------------------------------------
[2020-06-05 18:18:09.978 1790] Thank you for helping us to improve our FTL engine!
[2020-06-05 18:18:09.978 1790] FTL terminated!
[2020-06-05 18:23:17.635 20335] Using log file /var/log/pihole-FTL.log
[2020-06-05 18:23:17.636 20335] ########## FTL started! ##########

**Device specifics**

Hardware Type: rPi, VPS, etc
OS:

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment] 2020-06-05 18:22
Duplicate of https://github.com/pi-hole/FTL/issues/767

Please check for details there. Also, please attach the debugger as described in the other bug report. It would be nice if you could comment in there and say if you, e.g., use Cloudflare as upstream server or anything special like DoH, etc.

**Closed by DL6ER** 2020-06-05 18:22 UTC
