### ISSUE TITLE
dnsmasq failed during update 

### ISSUE THREAD

**Issue by pztop** [pi-hole/FTL#237] opened 2018-02-18 21:26 UTC
I was check the pi-hole and see new update is available so I login and tried to update, then I got this:
```root@pi-hole:~# pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     update available
  [i] FTL:              update available
  [i] Web Interface:    update available

  [i] Updating Pi-hole core and web admin files
  [✓] Check for existing repository in /etc/.pihole
  [✓] Update repo in /etc/.pihole


  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [✓] Disk space check

  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... 28 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [✓] Checking for dialog
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [✓] Check for existing repository in /etc/.pihole
  [✓] Update repo in /etc/.pihole

  [✓] Check for existing repository in /var/www/html/admin
  [✓] Update repo in /var/www/html/admin

  [i] Main Dependency checks...
  [✓] Checking for bc
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsmasq
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for lighttpd
  [✓] Checking for php5-common
  [✓] Checking for php5-cgi
  [✓] Checking for php5-sqlite

  [✓] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf

  [i] Creating log and changing owner to dnsmasq... log already exists!

  [i] Installing blocking page...
  [✓] Creating directory for blocking page, and copying files
  [✗] Backing up index.lighttpd.html
      No default index.lighttpd.html file found... not backing up

  [✓] Installing sudoer file

  [✓] Installing latest Cron script

  [✓] Installing latest logrotate script

  [i] FTL Checks...
  [✓] Detected x86_64 architecture
  [i] Checking for existing FTL binary...
  [✓] Downloading and Installing FTL
  [i] Restarting services...

  [i] Starting dnsmasq service...
  Unable to complete update, please contact Pi-hole Support
```

I checked system log and see:
```
Feb 18 13:00:19 pi-hole dnsmasq[549]: extraneous parameter at line 37 of /etc/dnsmasq.d/01-pihole.conf
Feb 18 13:00:19 pi-hole dnsmasq[549]: FAILED to start up
Feb 18 13:00:19 pi-hole systemd[1]: dnsmasq.service: control process exited, code=exited status=1
```
So I disabled line 37 in /etc/dnsmasq.d/01-pihole.conf
`#log-queries=extra`

Then I restarted dnsmasq and did update again. This time it went fine without error. I reboot my pi-hole server and check the webUI, at the bottom I still see:
`Pi-hole Version v3.2.1 (Update available!) Web Interface Version v3.3 FTL Version v3.0  `

I tried update again and it keep tell me "Update available".

So here I have 2 questions:
1. Do I need worry about the change in /etc/dnsmasq.d/01-pihole.conf ?
2. Did my update successes? If not what should I do to bring it up to date?

Thank you for help.

**Comment by dschaper** [comment] 2018-02-18 22:02
https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159

**Comment by pztop** [comment] 2018-02-18 23:36
Thank you for the info. 
My pi-hole is running on a VM on ESXi 6.5. Now I just did distro upgrade to Debian 9 and this bring dnsmasq to v2.76.  Now the pihole upgrade went fine without no error. 

It just when I check the webUI, on the bottom of the dashboard it's still saying:
`Pi-hole Version v3.2.1 (Update available!) Web Interface Version v3.3 FTL Version v3.0 `

Went back and try upgrade again:
```root@pi-hole:~# pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] FTL:              up to date
  [i] Web Interface:    up to date

  [✓] Everything is up to date!
```
Is this a bug? or I did something wrong?

**Comment by technicalpyro** [comment] 2018-02-19 01:54
what does `pihole -v` return from the CLI

**Comment by pztop** [comment] 2018-02-19 04:25
```
root@pi-hole:~# pihole -v
  Pi-hole version is v3.2.1-73-g1e87850 (Latest: v3.3)
  AdminLTE version is v3.3 (Latest: v3.3)
  FTL version is v3.0 (Latest: v3.0)
```

**Comment by Mcat12** [comment] 2018-02-19 04:51
From the link @dschaper posted:
```
cd /etc/.pihole
sudo git fetch --tags
```

**Comment by pztop** [comment] 2018-02-19 05:37
@Mcat12,  Well, I just want get the latest the update.  I see @dschaper post is talking about revert back to previous version.  I am running VM so if I need revert I can easily roll back to a previous snapshot.

**Comment by Mcat12** [comment] 2018-02-19 17:45
Those commands will fix the version issue.

**Comment by pztop** [comment] 2018-02-19 22:10
@Mcat12 You are right and I got the update issue fixed. Now pi-hole is on the latest version:
```root@pi-hole:~# pihole -v
  Pi-hole version is v3.3 (Latest: v3.3)
  AdminLTE version is v3.3 (Latest: v3.3)
  FTL version is v3.0 (Latest: v3.0)
```
I still have 2 issues: both "Tail pihole.log" and "Tail pihole-FTL.log" (under Tools) are not working.

**Comment by cshumac** [comment] 2018-03-14 00:41
I'm having a similar issue. I tried to update my pihole but am running Jessie. Now its borked. 

I've ran sudo git fetch --tags and get
fatal: unable to access 'https://github.com/pi-hole/pi-hole.git/': Could not resolve host: github.com

I can't seem to resolve github anymore so I can't pihole -r either.

**Comment by FlatCapElectronics** [comment] 2018-03-15 03:17
> fatal: unable to access 'https://github.com/pi-hole/pi-hole.git/': Could not resolve host: github.com
> I can't seem to resolve github anymore so I can't pihole -r either.

I had this too. I think the problem is that the pi has been configured by pihole to use itself as a dns server.
Try . . .
sudo nano /etc/resolv.conf
Change the nameserver to your router, or google, or whatever will work for the moment. I used my router.
This should get the pi speaking to the world again.

**Comment by cshumac** [comment] 2018-03-15 03:37
@FlatCapElectronics I think you nailed it! It took me a minute to figure out how to use Nano, but once I did, I was able to edit it and save it. Now, I've gone back to reverting to the older version. Looks like its up and running now, I'm going to test it out. Thank you for your help!

**Comment by cshumac** [comment] 2018-03-15 16:27
@FlatCapElectronics I'm not sure my PiHole is working still. Its not showing any blocked queries or any query history at all, and I'm definitely routing my DNS to it. At the bottom of the page it says I've gone back to the old version:
Pi-hole Version vDev (HEAD, v3.2.1-0-ge602008) Web Interface Version vDev (HEAD, v3.2.1-0-g31dddd8) FTL Version vDev (v3.0 , v3.0 )

pihole status says its running  and ad blocking is enabled. How can I get the dashboard to properly display that its working?

**Comment by FlatCapElectronics** [comment] 2018-03-15 19:02
@cshumac At this point I'm not sure, it's over my helmet. All I can do is guess, but we may have exceeded the context here. I'd try the [subreddit](https://www.reddit.com/r/pihole/) if you need further help, as you'll have the benefit of much more experienced people than me.
Mine is working, and my version string is:
    `Pi-hole Version vDev (HEAD, v3.2.1-0-ge602008) Web Interface Version vDev (HEAD, v3.2.1-0-g31dddd8) FTL Version vDev (v2.13.2 , v2.13.2 )`
I followed the instructions [here](https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159). (Search for "Update 2018-02-14 18:43")
Your version of FTL is different, and if you're using your pi as a DHCP server that may be a factor. You might try the last thing in the instructions from above:
`pihole checkout ftl v2.13.2`

**Comment by DL6ER** [comment] 2018-03-30 21:00
I'm closing this as the OP didn't respond for > 1 month and the issue report started to deviate into the Jessie update problem which has been discussed elsewhere extensively. @pztop feel free to re-open or open another issue report if you are still experiencing problems with FTL.

**Closed by DL6ER** 2018-03-30 21:00 UTC
