### ISSUE TITLE
 FTL crashed! 

### ISSUE THREAD

**Issue by AthrogatePEQ** [pi-hole/FTL#446] opened 2018-12-21 22:35 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1_

---

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**Log file output [if available]**

[2018-12-21 17:27:00.149] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2018-12-21 17:27:00.149] ---------------------------->  FTL crashed!  <----------------------------
[2018-12-21 17:27:00.149] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2018-12-21 17:27:00.149] Please report a bug at https://github.com/pi-hole/FTL/issues
[2018-12-21 17:27:00.149] and include in your report already the following details:

[2018-12-21 17:27:00.149] FTL has been running for 55 seconds
[2018-12-21 17:27:00.149] FTL branch: master
[2018-12-21 17:27:00.149] FTL version: v4.1.1
[2018-12-21 17:27:00.149] FTL commit: f5f331b
[2018-12-21 17:27:00.149] FTL date: 2018-12-21 10:32:10 -0600
[2018-12-21 17:27:00.149] FTL user: pihole
[2018-12-21 17:27:00.149] Received signal: Segmentation fault
[2018-12-21 17:27:00.149]      at address: 0
[2018-12-21 17:27:00.149]      with code: SEGV_MAPERR (Address not mapped to object)
[2018-12-21 17:27:00.150] Backtrace:
[2018-12-21 17:27:00.150] B[0000]: /usr/bin/pihole-FTL(+0x24f93) [0x55cd90915f93]
[2018-12-21 17:27:00.150] B[0001]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f57aed1c390]
[2018-12-21 17:27:00.150] B[0002]: /lib/x86_64-linux-gnu/libc.so.6(+0x9f58e) [0x7f57ae9e058e]
[2018-12-21 17:27:00.150] B[0003]: /usr/bin/pihole-FTL(FTL_reply+0x1ce) [0x55cd9091ff2e]
[2018-12-21 17:27:00.150] B[0004]: /usr/bin/pihole-FTL(cache_insert+0x143) [0x55cd90948053]
[2018-12-21 17:27:00.150] B[0005]: /usr/bin/pihole-FTL(extract_addresses+0xc9e) [0x55cd9093ebae]
[2018-12-21 17:27:00.150] B[0006]: /usr/bin/pihole-FTL(+0x3feda) [0x55cd90930eda]
[2018-12-21 17:27:00.150] B[0007]: /usr/bin/pihole-FTL(reply_query+0x4e9) [0x55cd909351e9]
[2018-12-21 17:27:00.150] B[0008]: /usr/bin/pihole-FTL(+0x579ac) [0x55cd909489ac]
[2018-12-21 17:27:00.150] B[0009]: /usr/bin/pihole-FTL(main_dnsmasq+0x105c) [0x55cd9094a41c]
[2018-12-21 17:27:00.150] B[0010]: /usr/bin/pihole-FTL(main+0xbb) [0x55cd909140cb]
[2018-12-21 17:27:00.150] B[0011]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f57ae961830]
[2018-12-21 17:27:00.150] B[0012]: /usr/bin/pihole-FTL(_start+0x2a) [0x55cd909141ca]
[2018-12-21 17:27:00.150] Thank you for helping us to improve our FTL engine!
[2018-12-21 17:27:00.150] FTL terminated!

**Device specifics**

Hardware Type: rPi, VPS, etc
OS:
root@dns:~# cat /etc/debian_version
stretch/sid

Running in a VMWare container on Mac OSX

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment] 2018-12-21 22:37
Please update to v4.1.2 that resolves this issue.

**Comment by dschaper** [comment] 2018-12-21 22:38
Duplicate of #444

**Closed by dschaper** 2018-12-21 22:38 UTC
