### ISSUE TITLE
 FTL crashed!

### ISSUE THREAD

**Issue by myrmidondvb** [pi-hole/FTL#518] opened 2019-02-20 14:15 UTC
[2019-02-19 18:00:00.687] Resizing "/FTL-s://github.com/pi-hole/FTL/issuestrings" from 57344 to 61440
[2019-02-19 21:28:00.864] Resizing "/FTL-strings" from 61440 to 65536
[2019-02-19 21:35:49.238] Resizing "/FTL-strings" from 65536 to 69632
[2019-02-19 22:15:17.007] Resizing "/FTL-strings" from 69632 to 73728
[2019-02-19 23:20:01.813] Resizing "(null)" from 473 to 19248
[2019-02-19 23:20:01.813] realloc_shm(): munmap(0x76efb7c4, 473) failed: Invalid argument
[2019-02-19 23:20:01.814] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2019-02-19 23:20:01.814] ---------------------------->  FTL crashed!  <----------------------------
[2019-02-19 23:20:01.814] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2019-02-19 23:20:01.814] Please report a bug at https://github.com/pi-hole/FTL/issues
[2019-02-19 23:20:01.814] and include in your report already the following details:

[2019-02-19 23:20:01.814] FTL has been running for 342166 seconds
[2019-02-19 23:20:01.814] FTL branch: master
[2019-02-19 23:20:01.814] FTL version: v4.2.1
[2019-02-19 23:20:01.815] FTL commit: 5f98312
[2019-02-19 23:20:01.815] FTL date: 2019-02-06 18:36:55 -0800
[2019-02-19 23:20:01.815] FTL user: started as pihole, ended as pihole
[2019-02-19 23:20:01.815] Received signal: Segmentation fault
[2019-02-19 23:20:01.815]      at address: 0
[2019-02-19 23:20:01.815]      with code: SEGV_MAPERR (Address not mapped to object)
[2019-02-19 23:20:01.816] Backtrace:
[2019-02-19 23:20:01.816] B[0000]: /usr/bin/pihole-FTL(+0x1a3e0) [0x4ee3e0]
[2019-02-19 23:20:01.816] B[0001]: /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0x76dec6c0]
[2019-02-19 23:20:01.816] Thank you for helping us to improve our FTL engine!
[2019-02-19 23:20:01.816] FTL terminated!

**Comment by Mcat12** [comment] 2019-02-20 15:55
Please update to v4.2.2

**Comment by meinhosterpro** [comment] 2019-02-20 19:44
[2019-02-20 20:26:49.094 7424] FTL has been running for 1886 seconds
[2019-02-20 20:26:49.094 7424] FTL branch: master
[2019-02-20 20:26:49.094 7424] FTL version: v4.2.2
[2019-02-20 20:26:49.094 7424] FTL commit: 4a8003c
[2019-02-20 20:26:49.094 7424] FTL date: 2019-02-18 18:30:16 +0100
[2019-02-20 20:26:49.094 7424] FTL user: started as pihole, ended as pihole
[2019-02-20 20:26:49.095 7424] Received signal: Segmentation fault
[2019-02-20 20:26:49.095 7424]      at address: 139784568631304
[2019-02-20 20:26:49.095 7424]      with code: SEGV_ACCERR (Invalid permissions for mapped object)
[2019-02-20 20:26:49.096 7424] Backtrace:
[2019-02-20 20:26:49.096 7424] B[0000]: /usr/bin/pihole-FTL(+0x251c8) [0x5577436071c8]
[2019-02-20 20:26:49.096 7424] B[0001]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0) [0x7f2226d040e0]
[2019-02-20 20:26:49.096 7424] B[0002]: /usr/bin/pihole-FTL(FTL_new_query+0x552) [0x557743610c02]
[2019-02-20 20:26:49.096 7424] B[0003]: /usr/bin/pihole-FTL(receive_query+0x9b2) [0x557743628112]
[2019-02-20 20:26:49.096 7424] B[0004]: /usr/bin/pihole-FTL(+0x5a9cb) [0x55774363c9cb]
[2019-02-20 20:26:49.096 7424] B[0005]: /usr/bin/pihole-FTL(main_dnsmasq+0xfdc) [0x55774363e3dc]
[2019-02-20 20:26:49.096 7424] B[0006]: /usr/bin/pihole-FTL(main+0xb7) [0x5577436056c7]
[2019-02-20 20:26:49.096 7424] B[0007]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f22269742e1]
[2019-02-20 20:26:49.096 7424] B[0008]: /usr/bin/pihole-FTL(_start+0x2a) [0x5577436057fa]
[2019-02-20 20:26:49.096 7424] Thank you for helping us to improve our FTL engine!
[2019-02-20 20:26:49.096 7424] FTL terminated!

**Comment by Sveeeeeen** [comment] 2019-02-21 00:27
Same issue:

`[2019-02-20 13:28:20.492 11210] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2019-02-20 13:28:20.492 11210] ---------------------------->  FTL crashed!  <----------------------------
[2019-02-20 13:28:20.492 11210] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2019-02-20 13:28:20.492 11210] Please report a bug at https://github.com/pi-hole/FTL/issues
[2019-02-20 13:28:20.492 11210] and include in your report already the following details:
[2019-02-20 13:28:20.492 11210] FTL has been running for 1434 seconds
[2019-02-20 13:28:20.492 11210] FTL branch: master
[2019-02-20 13:28:20.492 11210] FTL version: v4.2.2
[2019-02-20 13:28:20.492 11210] FTL commit: 4a8003c
[2019-02-20 13:28:20.492 11210] FTL date: 2019-02-18 18:30:16 +0100
[2019-02-20 13:28:20.492 11210] FTL user: started as pihole, ended as pihole
[2019-02-20 13:28:20.492 11210] Received signal: Segmentation fault
[2019-02-20 13:28:20.492 11210]      at address: 140008660844552
[2019-02-20 13:28:20.492 11210]      with code: SEGV_ACCERR (Invalid permissions for mapped object)
[2019-02-20 13:28:20.493 11210] Backtrace:
[2019-02-20 13:28:20.493 11210] B[0000]: /usr/bin/pihole-FTL(+0x251c8) [0x55fb2a5751c8]
[2019-02-20 13:28:20.493 11210] B[0001]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x12890) [0x7f56583ce890]
[2019-02-20 13:28:20.494 11210] B[0002]: /usr/bin/pihole-FTL(FTL_new_query+0x552) [0x55fb2a57ec02]
[2019-02-20 13:28:20.494 11210] B[0003]: /usr/bin/pihole-FTL(tcp_request+0x778) [0x55fb2a593dd8]
[2019-02-20 13:28:20.494 11210] B[0004]: /usr/bin/pihole-FTL(+0x5a874) [0x55fb2a5aa874]
[2019-02-20 13:28:20.494 11210] B[0005]: /usr/bin/pihole-FTL(main_dnsmasq+0xfdc) [0x55fb2a5ac3dc]
[2019-02-20 13:28:20.494 11210] B[0006]: /usr/bin/pihole-FTL(main+0xb7) [0x55fb2a5736c7]
[2019-02-20 13:28:20.494 11210] B[0007]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f5657fecb97]
[2019-02-20 13:28:20.494 11210] B[0008]: /usr/bin/pihole-FTL(_start+0x2a) [0x55fb2a5737fa]
[2019-02-20 13:28:20.494 11210] Thank you for helping us to improve our FTL engine!
[2019-02-20 13:28:20.494 11210] FTL terminated!
[2019-02-20 13:28:20.703 3277] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2019-02-20 13:28:20.704 3277] ---------------------------->  FTL crashed!  <----------------------------
[2019-02-20 13:28:20.704 3277] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2019-02-20 13:28:20.704 3277] Please report a bug at https://github.com/pi-hole/FTL/issues
[2019-02-20 13:28:20.704 3277] and include in your report already the following details:
[2019-02-20 13:28:20.704 3277] FTL has been running for 1434 seconds
[2019-02-20 13:28:20.704 3277] FTL branch: master
[2019-02-20 13:28:20.704 3277] FTL version: v4.2.2
[2019-02-20 13:28:20.704 3277] FTL commit: 4a8003c
[2019-02-20 13:28:20.704 3277] FTL date: 2019-02-18 18:30:16 +0100
[2019-02-20 13:28:20.704 3277] FTL user: started as pihole, ended as pihole
[2019-02-20 13:28:20.704 3277] Received signal: Segmentation fault
[2019-02-20 13:28:20.704 3277]      at address: 140008660844552
[2019-02-20 13:28:20.704 3277]      with code: SEGV_ACCERR (Invalid permissions for mapped object)
[2019-02-20 13:28:20.704 3277] Backtrace:
[2019-02-20 13:28:20.704 3277] B[0000]: /usr/bin/pihole-FTL(+0x251c8) [0x55fb2a5751c8]
[2019-02-20 13:28:20.704 3277] B[0001]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x12890) [0x7f56583ce890]
[2019-02-20 13:28:20.704 3277] B[0002]: /usr/bin/pihole-FTL(FTL_new_query+0x552) [0x55fb2a57ec02]
[2019-02-20 13:28:20.704 3277] B[0003]: /usr/bin/pihole-FTL(receive_query+0x9b2) [0x55fb2a596112]
[2019-02-20 13:28:20.704 3277] B[0004]: /usr/bin/pihole-FTL(+0x5a9cb) [0x55fb2a5aa9cb]
[2019-02-20 13:28:20.704 3277] B[0005]: /usr/bin/pihole-FTL(main_dnsmasq+0xfdc) [0x55fb2a5ac3dc]
[2019-02-20 13:28:20.704 3277] B[0006]: /usr/bin/pihole-FTL(main+0xb7) [0x55fb2a5736c7]
[2019-02-20 13:28:20.704 3277] B[0007]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f5657fecb97]
[2019-02-20 13:28:20.704 3277] B[0008]: /usr/bin/pihole-FTL(_start+0x2a) [0x55fb2a5737fa]
[2019-02-20 13:28:20.704 3277] Thank you for helping us to improve our FTL engine!
[2019-02-20 13:28:20.704 3277] FTL terminated!`

**Comment by Sveeeeeen** [comment] 2019-02-21 01:20
Again:

> [2019-02-21 01:28:27.487 1225] Skipping empty regex filter on line 1
[2019-02-21 01:28:27.488 1225] Compiled 3 Regex filters and 8 whitelisted domains in 0.7 msec (0 errors)
[2019-02-21 01:28:27.488 1225] /etc/pihole/black.list: parsed 0 domains (took 0.0 ms)
[2019-02-21 01:28:28.569 1225] /etc/pihole/gravity.list: parsed 112231 domains (took 1081.0 ms)
[2019-02-21 01:28:54.204 1225] Resizing "/FTL-strings" from 28672 to 32768
[2019-02-21 01:28:55.092 1225] Resizing "/FTL-queries" from 6193152 to 6488064
[2019-02-21 01:33:15.703 1225] Resizing "/FTL-queries" from 6488064 to 6782976
[2019-02-21 01:38:31.433 1225] Resizing "/FTL-queries" from 6782976 to 7077888
[2019-02-21 01:43:29.794 5712] Resizing "/FTL-queries" from 7077888 to 7372800
[2019-02-21 01:43:29.813 1225] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2019-02-21 01:43:29.813 1225] ---------------------------->  FTL crashed!  <----------------------------
[2019-02-21 01:43:29.813 1225] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2019-02-21 01:43:29.813 1225] Please report a bug at https://github.com/pi-hole/FTL/issues
[2019-02-21 01:43:29.813 1225] and include in your report already the following details:
[2019-02-21 01:43:29.813 1225] FTL has been running for 903 seconds
[2019-02-21 01:43:29.813 1225] FTL branch: master
[2019-02-21 01:43:29.813 1225] FTL version: v4.2.2
[2019-02-21 01:43:29.813 1225] FTL commit: 4a8003c
[2019-02-21 01:43:29.813 1225] FTL date: 2019-02-18 18:30:16 +0100
[2019-02-21 01:43:29.814 1225] FTL user: started as pihole, ended as pihole
[2019-02-21 01:43:29.814 1225] Received signal: Segmentation fault
[2019-02-21 01:43:29.814 1225]      at address: 140094197633032
[2019-02-21 01:43:29.814 1225]      with code: SEGV_ACCERR (Invalid permissions for mapped object)
[2019-02-21 01:43:29.814 1225] Backtrace:
[2019-02-21 01:43:29.815 1225] B[0000]: /usr/bin/pihole-FTL(+0x251c8) [0x55b7840a81c8]
[2019-02-21 01:43:29.815 1225] B[0001]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x12890) [0x7f6a3dafe890]
[2019-02-21 01:43:29.815 1225] B[0002]: /usr/bin/pihole-FTL(FTL_new_query+0x552) [0x55b7840b1c02]
[2019-02-21 01:43:29.815 1225] B[0003]: /usr/bin/pihole-FTL(receive_query+0x9b2) [0x55b7840c9112]
[2019-02-21 01:43:29.815 1225] B[0004]: /usr/bin/pihole-FTL(+0x5a9cb) [0x55b7840dd9cb]
[2019-02-21 01:43:29.815 1225] B[0005]: /usr/bin/pihole-FTL(main_dnsmasq+0xfdc) [0x55b7840df3dc]
[2019-02-21 01:43:29.815 1225] B[0006]: /usr/bin/pihole-FTL(main+0xb7) [0x55b7840a66c7]
[2019-02-21 01:43:29.815 1225] B[0007]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f6a3d71cb97]
[2019-02-21 01:43:29.815 1225] B[0008]: /usr/bin/pihole-FTL(_start+0x2a) [0x55b7840a67fa]
[2019-02-21 01:43:29.815 1225] Thank you for helping us to improve our FTL engine!
[2019-02-21 01:43:29.815 1225] FTL terminated!

**Comment by Mcat12** [comment] 2019-02-21 01:35
Duplicate of #496

**Closed by Mcat12** 2019-02-21 01:35 UTC
