### ISSUE TITLE
Latest v6 causes lag in database operation and CPU spikes

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/FTL#1692] opened 2023-10-23 18:44 UTC
Enabling/Disabling adlists is very laggy compared to previous development versions and causes high CPU spikes up to 100%

![Peek 2023-10-23 20-39](https://github.com/pi-hole/FTL/assets/26622301/cc5087c4-1e97-48de-8177-4d9403c7701b)

```
  Current Pi-hole version is development-v6 v5.17.1-189-ga44e51b
  Current web version is development-v6 v5.19-352-g48fd33bf
  Current FTL version is development-v6 vDev-8664165
```

**Comment by yubiuser** [comment] 2023-10-23 18:44
Might be related to the transaction PR.

**Comment by DL6ER** [comment] 2023-10-23 19:20
We need more context to debug this. Firstly, I'd propose enabling custom thread names in `htop` so we can see which thread is really spiking here:

![Screenshot from 2023-10-23 21-10-17](https://github.com/pi-hole/FTL/assets/16748619/347f4ff2-dccb-4b87-945c-b08cc30585a4)

Also, it might be worth enabling all kinds of debug flags (possibly even all of them) and then check the logs for the reason of the delay.

**Comment by yubiuser** [comment] 2023-10-23 19:26
It's `civetweb-worker`

**Comment by DL6ER** [comment] 2023-10-23 19:27
Okay, so it is the API itself - that's interesting. More debug output appreciated :-)

**Comment by yubiuser** [comment] 2023-10-23 19:31
[log.log](https://github.com/pi-hole/FTL/files/13078531/log.log)

**Comment by DL6ER** [comment] 2023-10-23 19:39
This is indeed strange, let me quote a few selected lines here
```
2023-10-23 21:27:02.706 [229370/T229404] DEBUG_API: Processing PUT /api/lists/https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt in /api/lists
[...]
2023-10-23 21:27:02.706 [229370/T229404] DEBUG_LOCKS: Obtained SHM lock for api_list() (/app/src/api/list.c:483)
```
The request is received, and the lock is immediately assigned, that's good, but then
```
2023-10-23 21:27:04.111 [229370/T229404] DEBUG_API: SQL: REPLACE INTO adlist (address,enabled,comment,type,id,date_added,date_updated,number,invalid_domains,status,abp_entries) VALUES (:item,:enabled,:comment,:type,(SELECT id FROM adlist WHERE address = :item),(SELECT date_added FROM adlist WHERE address = :item),(SELECT date_updated FROM adlist WHERE address = :item),(SELECT number FROM adlist WHERE address = :item),(SELECT invalid_domains FROM adlist WHERE address = :item),(SELECT status FROM adlist WHERE address = :item),(SELECT abp_entries FROM adlist WHERE address = :item));

```
happens only 1.4 seconds later with no other log lines in between. Why did it take so long?...

The API request itself is finished very soon after,
```
2023-10-23 21:27:04.167 [229370/T229404] DEBUG_API: Done
```
triggering a gravity reloading
```
2023-10-23 21:27:04.173 [229370/T229395] DEBUG_EVENTS: Event RELOAD_GRAVITY -> was SET, now CLEARED    called from DB_thread() (/app/src/database/database-thread.c:177)
```
which takes around 0.1 second
```
2023-10-23 21:27:04.285 [229370/T229395] INFO: Compiled 2 allow and 1 deny regex for 1 client in 38.2 msec
```

---

We see similar delays later on
```
2023-10-23 21:26:57.506 [229370/T229408] DEBUG_API: Processing PUT /api/lists/https://small.oisd.nl/ in /api/lists
[...]
2023-10-23 21:26:59.215 [229370/T229408] DEBUG_API: SQL: REPLACE INTO adlist (address,enabled,comment,type,id,date_added,date_updated,number,invalid_domains,status,abp_entries) VALUES (:item,:enabled,:comment,:type,(SELECT id FROM adlist WHERE address = :item),(SELECT date_added FROM adlist WHERE address = :item),(SELECT date_updated FROM adlist WHERE address = :item),(SELECT number FROM adlist WHERE address = :item),(SELECT invalid_domains FROM adlist WHERE address = :item),(SELECT status FROM adlist WHERE address = :item),(SELECT abp_entries FROM adlist WHERE address = :item));
```

---

I'll try to reproduce this myself

**Comment by yubiuser** [comment] 2023-10-23 19:41
I use a low-end hardware device, you might be unable to reproduce this with sufficient power.

**Comment by DL6ER** [comment] 2023-10-23 19:46
I can confirm a delay of 0.2 seconds:
```
2023-10-23 21:45:39.550 [854651/T854669] DEBUG_API: Processing PUT /api/lists/https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts in /api/lists
2023-10-23 21:45:39.756 [854651/T854669] DEBUG_API: SQL: REPLACE INTO adlist (address,enabled,comment,type,id,date_added,date_updated,number,invalid_domains,status,abp_entries) VALUES (:item,:enabled,:comment,:type,(SELECT id FROM adlist WHERE address = :item),(SELECT date_added FROM adlist WHERE address = :item),(SELECT date_updated FROM adlist WHERE address = :item),(SELECT number FROM adlist WHERE address = :item),(SELECT invalid_domains FROM adlist WHERE address = :item),(SELECT status FROM adlist WHERE address = :item),(SELECT abp_entries FROM adlist WHERE address = :item));
```

since my Pi-hole is running on high-end hardware, that is surely somewhat concerning. Investigation ongoing...

**Comment by DL6ER** [comment] 2023-10-23 20:36
I traced it down. It is in fact the `REPLACE INTO adlist ...` call to the database that is taking so long. A deeper dive into the inner guts of SQLite3 showed a profile where > 99% of the time is spent to check if this update would violate a foreign key constraint. As there are no foreign key related changes are happening when *modifying* entries, the solution is either one of:

1. Disable foreign key checks
2. Use another method that makes sure SQLite3 sees there there cannot be a foreign key conflict here.

I will go for the second option.

**Comment by DL6ER** [comment] 2023-10-23 20:38
Should be fixed by https://github.com/pi-hole/FTL/pull/1695

**Comment by yubiuser** [comment] 2023-10-24 20:00
With the fix it's fast now

```
2023-10-24 21:58:57.634 [240977/T240990] DEBUG_API: Processing PUT /api/lists/https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/domains.txt in /api/lists
2023-10-24 21:58:57.646 [240977/T240990] DEBUG_API: SQL: INSERT INTO adlist (address,enabled,comment,type) VALUES (:item,:enabled,:comment,:type) ON CONFLICT(address) DO UPDATE SET enabled = :enabled, comment = :comment, type = :type;
```

**Closed** 2023-10-24 20:00 UTC
