### ISSUE TITLE
conditional forwarding does not work anymore

### ISSUE THREAD

**Issue by WiredLife** [pi-hole/FTL#1254] opened 2021-12-11 01:16 UTC
### Versions
- Pi-hole:  v5.6 (Latest: v5.6)
- AdminLTE:  v5.8 (Latest: v5.8)
- FTL:  v5.11 (Latest: v5.11)

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster) 5.10.17-v7l+
- Platform:  Raspberry Pi 4

i dont know which update has killed it but now it doesnt work anymore

01-pihole.conf:
[01-pihole.conf.txt](https://github.com/pi-hole/pi-hole/files/7696177/01-pihole.conf.txt)

setupVars.conf has this:
REV_SERVER=true
REV_SERVER_CIDR=192.168.176.0/24
REV_SERVER_TARGET=192.168.176.1
REV_SERVER_DOMAIN=Lunochod

root@Pi-hole-RPi4:~# dig jule-smartphone.lunochod

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> jule-smartphone.lunochod
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 23671
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;jule-smartphone.lunochod.      IN      A

;; AUTHORITY SECTION:
.                       3553    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2021121001 1800 900 604800 86400

;; Query time: 78 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Dec 11 02:03:41 CET 2021
;; MSG SIZE  rcvd: 128

root@Pi-hole-RPi4:~# dig bernd-sat.filmfreunde

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> bernd-sat.filmfreunde
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 64004
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;bernd-sat.filmfreunde.         IN      A

;; AUTHORITY SECTION:
.                       3500    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2021121001 1800 900 604800 86400

;; Query time: 41 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Dec 11 02:04:34 CET 2021
;; MSG SIZE  rcvd: 125

and when i try it directly:
root@Pi-hole-RPi4:~# dig @192.168.176.1 -p 23553 jule-smartphone.lunochod

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> @192.168.176.1 -p 23553 jule-smartphone.lunochod
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25315
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;jule-smartphone.lunochod.      IN      A

;; ANSWER SECTION:
jule-smartphone.lunochod. 3600  IN      A       192.168.176.31

;; Query time: 0 msec
;; SERVER: 192.168.176.1#23553(192.168.176.1)
;; WHEN: Sat Dec 11 02:04:57 CET 2021
;; MSG SIZE  rcvd: 69

root@Pi-hole-RPi4:~# dig @192.168.178.1 -p 23553 bernd-sat.filmfreunde

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Raspbian <<>> @192.168.178.1 -p 23553 bernd-sat.filmfreunde
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54961
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;bernd-sat.filmfreunde.         IN      A

;; ANSWER SECTION:
bernd-sat.filmfreunde.  3600    IN      A       192.168.178.10

;; Query time: 17 msec
;; SERVER: 192.168.178.1#23553(192.168.178.1)
;; WHEN: Sat Dec 11 02:05:13 CET 2021
;; MSG SIZE  rcvd: 66

please help me

**Comment by yubiuser** [comment] 2021-12-13 20:49
I can confirm the behavior. If your dnsmasq config contains line `server` line containing an upper-case letter it will be ignored. This is likely a bug in `dnsmasq`

Pining @DL6ER if 

https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=e3093b532c34a8d95c8c751bdd9cabf552f5bf05 

does fix the issue described here.

**Comment by yubiuser** [comment] 2021-12-13 21:41
Workaround is to change all upper-case letters in your `server=` config to lower-case letters.

**Comment by DL6ER** [comment] 2021-12-14 09:31
This is a new bug we inherited from the upstream project `dnsmasq`. The linked Discourse thread has nothing to do with the current issue, it just happened to show the same symptoms. A fix for this bug is there since about two weeks in our branch that follows upstream development of `dnsmasq`. It is still in testing which is why it hasn't been released, so far. We are targeting a release still this year including this fix (this isn't a promise!).

> Pining @DL6ER if
> https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=e3093b532c34a8d95c8c751bdd9cabf552f5bf05
> does fix the issue described here.

@yubiuser Yes, it should fix the issue at hand. `address`, `server`, and `local` are using the same code for domain comparison. 

@WiredLife Please run
```
pihole checkout ftl update/dnsmasq
```
to get the latest code and check if the issue is fixed. If not, please describe what you are seeing. You can then still use the workaround mentioned in the previous comment:
> Workaround is to change all upper-case letters in your `server=` config to lower-case letters.

**Comment by WiredLife** [comment] 2021-12-16 03:21
after "pihole checkout ftl update/dnsmasq" everything work as expected

**Comment by DL6ER** [comment] 2021-12-22 20:33
The next version of FTL has been released. Please update and run
```
pihole checkout master
```
to get back on-track. The fix/feature branch you switched to will not receive any further updates.

Thanks for helping us to make Pi-hole better for us all!

If you have any issues, please either reopen this ticket or (preferably) create a new ticket describing the issues in further detail and only reference this ticket. This will help us to help you best.

**Closed by DL6ER** 2021-12-22 20:33 UTC
Labels: Fixed in next release, dnsmasq bug
