### ISSUE TITLE
FTL shows "Update available" ... but installs 5.3.4 again ?

### ISSUE THREAD

**Issue by roe1974** [pi-hole/FTL#1020] opened 2021-01-15 11:54 UTC
### Versions

- Pi-hole:  5.2.2
- AdminLTE:  5.2.2
- FTL:  5.3.4

### Platform

- OS and version:  RaspiOS Buster

- Platform:  Raspian

A pihole -up brings an update for the FTL ... but 5.3.4 is allready installed !?!?

br, Richard

**Comment by yubiuser** [comment] 2021-01-15 12:08
Thanks for the report.
It's a duplicate of
pi-hole/pi-hole#3986

**Closed** 2021-01-15 12:10 UTC
